import {
  HousekeepingStaff,
  HousekeepingTaskEnhanced,
  LostFoundItem,
  LinenItem,
  LinenLocationStock,
  LinenTransaction,
  HousekeepingAmenity,
  AmenityConsumptionRecord,
  HousekeepingRequest,
  RoomDiscrepancyRecord,
  HousekeepingShiftRecord,
  RoomInspectionRecord
} from '../types/housekeeping';

export const SEED_HK_STAFF: HousekeepingStaff[] = [
  {
    id: 'hks-1',
    name: 'Fatema Begum',
    employeeCode: 'EMP-HK-001',
    role: 'Attendant',
    shift: 'Morning',
    phone: '+880 1711-234501',
    active: true,
    assignedFloor: 1,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    currentActiveRoomsCount: 4
  },
  {
    id: 'hks-2',
    name: 'Rahim Uddin',
    employeeCode: 'EMP-HK-002',
    role: 'Attendant',
    shift: 'Morning',
    phone: '+880 1711-234502',
    active: true,
    assignedFloor: 2,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    currentActiveRoomsCount: 3
  },
  {
    id: 'hks-3',
    name: 'Salma Khatun',
    employeeCode: 'EMP-HK-003',
    role: 'Attendant',
    shift: 'Morning',
    phone: '+880 1711-234503',
    active: true,
    assignedFloor: 3,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    currentActiveRoomsCount: 4
  },
  {
    id: 'hks-4',
    name: 'Jannat Ara',
    employeeCode: 'EMP-HK-004',
    role: 'Attendant',
    shift: 'Morning',
    phone: '+880 1711-234504',
    active: true,
    assignedFloor: 'VIP Floor',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    currentActiveRoomsCount: 2
  },
  {
    id: 'hks-5',
    name: 'Kabir Hossain',
    employeeCode: 'EMP-HK-005',
    role: 'Attendant',
    shift: 'Evening',
    phone: '+880 1711-234505',
    active: true,
    assignedFloor: 1,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    currentActiveRoomsCount: 2
  },
  {
    id: 'hks-6',
    name: 'Rubel Mia',
    employeeCode: 'EMP-HK-006',
    role: 'Attendant',
    shift: 'Evening',
    phone: '+880 1711-234506',
    active: true,
    assignedFloor: 2,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    currentActiveRoomsCount: 1
  },
  {
    id: 'hks-7',
    name: 'Shamsul Huda',
    employeeCode: 'EMP-HK-101',
    role: 'Supervisor',
    shift: 'Morning',
    phone: '+880 1711-234510',
    active: true,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'hks-8',
    name: 'Nasreen Akter',
    employeeCode: 'EMP-HK-102',
    role: 'Supervisor',
    shift: 'Evening',
    phone: '+880 1711-234511',
    active: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'hks-9',
    name: 'Mahmudul Hasan',
    employeeCode: 'EMP-HK-201',
    role: 'Executive Housekeeper',
    shift: 'Morning',
    phone: '+880 1711-234520',
    active: true,
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'hks-10',
    name: 'Anisur Rahman',
    employeeCode: 'EMP-HK-301',
    role: 'Laundry Operator',
    shift: 'Morning',
    phone: '+880 1711-234530',
    active: true
  }
];

export const SEED_HK_TASKS: HousekeepingTaskEnhanced[] = [
  {
    id: 'hkt-101',
    taskNumber: 'TSK-2026-0901',
    roomId: 'rm-101',
    roomNumber: '101',
    roomTypeName: 'Deluxe Couple Room',
    floor: 1,
    cleaningType: 'Checkout Cleaning',
    priority: 'High',
    isVip: false,
    assignedAttendantId: 'hks-1',
    assignedAttendantName: 'Fatema Begum',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    status: 'In Progress',
    startedAt: '2026-09-01T09:15:00.000Z',
    estimatedDurationMinutes: 35,
    checklist: {
      bedLinenChanged: true,
      pillowCasesReplaced: true,
      bathroomSanitized: true,
      towelsReplaced: false,
      amenitiesRestocked: false,
      floorVacuumedMopped: false,
      dustingSurfacesCleaned: true,
      trashEmptied: true,
      minibarChecked: true,
      acTvWorking: true,
      odorFree: true
    },
    remarks: 'Guest checked out at 09:00 AM. In-progress turnover for 2:00 PM check-in.',
    createdAt: '2026-09-01T09:05:00.000Z',
    updatedAt: '2026-09-01T09:15:00.000Z',
    history: [
      { timestamp: '2026-09-01T09:05:00.000Z', action: 'Task Created', user: 'System (Front Desk Checkout)', notes: 'Auto generated on checkout' },
      { timestamp: '2026-09-01T09:10:00.000Z', action: 'Assigned Attendant', user: 'Shamsul Huda', notes: 'Assigned to Fatema Begum' },
      { timestamp: '2026-09-01T09:15:00.000Z', action: 'Cleaning Started', user: 'Fatema Begum', notes: 'Attendant unlocked room and commenced sanitization' }
    ]
  },
  {
    id: 'hkt-102',
    taskNumber: 'TSK-2026-0902',
    roomId: 'rm-102',
    roomNumber: '102',
    roomTypeName: 'Deluxe Twin Room',
    floor: 1,
    cleaningType: 'Stayover Cleaning',
    priority: 'Normal',
    isVip: false,
    assignedAttendantId: 'hks-1',
    assignedAttendantName: 'Fatema Begum',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    status: 'Cleaned',
    startedAt: '2026-09-01T08:30:00.000Z',
    completedAt: '2026-09-01T08:55:00.000Z',
    estimatedDurationMinutes: 25,
    actualDurationMinutes: 25,
    checklist: {
      bedLinenChanged: true,
      pillowCasesReplaced: true,
      bathroomSanitized: true,
      towelsReplaced: true,
      amenitiesRestocked: true,
      floorVacuumedMopped: true,
      dustingSurfacesCleaned: true,
      trashEmptied: true,
      minibarChecked: true,
      acTvWorking: true,
      odorFree: true
    },
    remarks: 'Daily tidy up and towel refresh completed.',
    createdAt: '2026-09-01T08:00:00.000Z',
    updatedAt: '2026-09-01T08:55:00.000Z',
    history: [
      { timestamp: '2026-09-01T08:00:00.000Z', action: 'Task Created', user: 'Shamsul Huda', notes: 'Daily morning stayover schedule' },
      { timestamp: '2026-09-01T08:30:00.000Z', action: 'Cleaning Started', user: 'Fatema Begum' },
      { timestamp: '2026-09-01T08:55:00.000Z', action: 'Cleaning Completed', user: 'Fatema Begum', notes: 'Ready for inspection' }
    ]
  },
  {
    id: 'hkt-103',
    taskNumber: 'TSK-2026-0903',
    roomId: 'rm-203',
    roomNumber: '203',
    roomTypeName: 'Executive Suite',
    floor: 2,
    guestName: 'Tariqul Islam',
    cleaningType: 'Stayover Cleaning',
    priority: 'High',
    isVip: true,
    assignedAttendantId: 'hks-2',
    assignedAttendantName: 'Rahim Uddin',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    status: 'Inspection Pending',
    startedAt: '2026-09-01T09:00:00.000Z',
    completedAt: '2026-09-01T09:35:00.000Z',
    estimatedDurationMinutes: 35,
    actualDurationMinutes: 35,
    checklist: {
      bedLinenChanged: true,
      pillowCasesReplaced: true,
      bathroomSanitized: true,
      towelsReplaced: true,
      amenitiesRestocked: true,
      floorVacuumedMopped: true,
      dustingSurfacesCleaned: true,
      trashEmptied: true,
      minibarChecked: true,
      acTvWorking: true,
      odorFree: true
    },
    remarks: 'VIP guest in-house. High thread-count linen replaced. Flowers refreshed.',
    createdAt: '2026-09-01T08:15:00.000Z',
    updatedAt: '2026-09-01T09:35:00.000Z',
    history: [
      { timestamp: '2026-09-01T08:15:00.000Z', action: 'Task Created', user: 'Shamsul Huda' },
      { timestamp: '2026-09-01T09:00:00.000Z', action: 'Cleaning Started', user: 'Rahim Uddin' },
      { timestamp: '2026-09-01T09:35:00.000Z', action: 'Submitted for Inspection', user: 'Rahim Uddin' }
    ]
  },
  {
    id: 'hkt-104',
    taskNumber: 'TSK-2026-0904',
    roomId: 'rm-305',
    roomNumber: '305',
    roomTypeName: 'Presidential Suite',
    floor: 3,
    guestName: 'Mahbubur Rahman (VIP)',
    cleaningType: 'VIP Cleaning',
    priority: 'VIP',
    isVip: true,
    assignedAttendantId: 'hks-4',
    assignedAttendantName: 'Jannat Ara',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    status: 'In Progress',
    startedAt: '2026-09-01T09:40:00.000Z',
    estimatedDurationMinutes: 60,
    checklist: {
      bedLinenChanged: true,
      pillowCasesReplaced: true,
      bathroomSanitized: true,
      towelsReplaced: true,
      amenitiesRestocked: false,
      floorVacuumedMopped: false,
      dustingSurfacesCleaned: false,
      trashEmptied: true,
      minibarChecked: true,
      acTvWorking: true,
      odorFree: true
    },
    remarks: 'VIP arrival scheduled for 03:00 PM. Premium aroma diffuser and fresh fruit basket setup required.',
    createdAt: '2026-09-01T09:00:00.000Z',
    updatedAt: '2026-09-01T09:40:00.000Z',
    history: [
      { timestamp: '2026-09-01T09:00:00.000Z', action: 'Task Created', user: 'Mahmudul Hasan', notes: 'VIP Arrival Turnover' },
      { timestamp: '2026-09-01T09:40:00.000Z', action: 'Cleaning Started', user: 'Jannat Ara' }
    ]
  },
  {
    id: 'hkt-105',
    taskNumber: 'TSK-2026-0905',
    roomId: 'rm-201',
    roomNumber: '201',
    roomTypeName: 'Executive Suite',
    floor: 2,
    cleaningType: 'Deep Cleaning',
    priority: 'Normal',
    isVip: false,
    assignedAttendantId: 'hks-2',
    assignedAttendantName: 'Rahim Uddin',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    status: 'Pending',
    estimatedDurationMinutes: 50,
    checklist: {
      bedLinenChanged: false,
      pillowCasesReplaced: false,
      bathroomSanitized: false,
      towelsReplaced: false,
      amenitiesRestocked: false,
      floorVacuumedMopped: false,
      dustingSurfacesCleaned: false,
      trashEmptied: false,
      minibarChecked: false,
      acTvWorking: false,
      odorFree: false
    },
    remarks: 'Scheduled monthly deep sanitization and curtain steam clean.',
    createdAt: '2026-09-01T08:30:00.000Z',
    updatedAt: '2026-09-01T08:30:00.000Z',
    history: [
      { timestamp: '2026-09-01T08:30:00.000Z', action: 'Task Created', user: 'Shamsul Huda' }
    ]
  },
  {
    id: 'hkt-106',
    taskNumber: 'TSK-2026-0906',
    roomId: 'rm-105',
    roomNumber: '105',
    roomTypeName: 'Deluxe Twin Room',
    floor: 1,
    cleaningType: 'Post-Maintenance Cleaning',
    priority: 'Urgent',
    isVip: false,
    assignedAttendantId: 'hks-1',
    assignedAttendantName: 'Fatema Begum',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    status: 'Assigned',
    estimatedDurationMinutes: 30,
    checklist: {
      bedLinenChanged: false,
      pillowCasesReplaced: false,
      bathroomSanitized: false,
      towelsReplaced: false,
      amenitiesRestocked: false,
      floorVacuumedMopped: false,
      dustingSurfacesCleaned: false,
      trashEmptied: false,
      minibarChecked: false,
      acTvWorking: false,
      odorFree: false
    },
    remarks: 'AC technician completed repair. Floor cleaning and air deodorization needed immediately.',
    createdAt: '2026-09-01T09:20:00.000Z',
    updatedAt: '2026-09-01T09:25:00.000Z',
    history: [
      { timestamp: '2026-09-01T09:20:00.000Z', action: 'Task Created', user: 'Maintenance Integration' },
      { timestamp: '2026-09-01T09:25:00.000Z', action: 'Assigned Attendant', user: 'Shamsul Huda', notes: 'Assigned to Fatema Begum' }
    ]
  },
  {
    id: 'hkt-107',
    taskNumber: 'TSK-2026-0907',
    roomId: 'rm-205',
    roomNumber: '205',
    roomTypeName: 'Deluxe Couple Room',
    floor: 2,
    cleaningType: 'Checkout Cleaning',
    priority: 'High',
    isVip: false,
    assignedAttendantId: 'hks-3',
    assignedAttendantName: 'Salma Khatun',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    status: 'Inspected',
    startedAt: '2026-09-01T07:45:00.000Z',
    completedAt: '2026-09-01T08:15:00.000Z',
    inspectedAt: '2026-09-01T08:25:00.000Z',
    estimatedDurationMinutes: 30,
    actualDurationMinutes: 30,
    checklist: {
      bedLinenChanged: true,
      pillowCasesReplaced: true,
      bathroomSanitized: true,
      towelsReplaced: true,
      amenitiesRestocked: true,
      floorVacuumedMopped: true,
      dustingSurfacesCleaned: true,
      trashEmptied: true,
      minibarChecked: true,
      acTvWorking: true,
      odorFree: true
    },
    inspectionPassed: true,
    inspectionRemarks: 'Pristine condition. Verified spotless bathroom and replenished mini-bar.',
    remarks: 'Ready for immediate Front Office guest check-in.',
    createdAt: '2026-09-01T07:30:00.000Z',
    updatedAt: '2026-09-01T08:25:00.000Z',
    history: [
      { timestamp: '2026-09-01T07:30:00.000Z', action: 'Task Created', user: 'System (Front Desk)' },
      { timestamp: '2026-09-01T07:45:00.000Z', action: 'Cleaning Started', user: 'Salma Khatun' },
      { timestamp: '2026-09-01T08:15:00.000Z', action: 'Cleaning Completed', user: 'Salma Khatun' },
      { timestamp: '2026-09-01T08:25:00.000Z', action: 'Inspection Approved', user: 'Shamsul Huda', notes: 'Score: 100%. Room updated to Vacant Clean' }
    ]
  }
];

export const SEED_INSPECTIONS: RoomInspectionRecord[] = [
  {
    id: 'ins-101',
    inspectionNumber: 'INS-2026-0081',
    roomId: 'rm-205',
    roomNumber: '205',
    roomTypeName: 'Deluxe Couple Room',
    supervisorId: 'hks-7',
    supervisorName: 'Shamsul Huda',
    attendantId: 'hks-3',
    attendantName: 'Salma Khatun',
    inspectionDate: '2026-09-01T08:25:00.000Z',
    overallResult: 'Pass',
    scorePercent: 100,
    remarks: 'Exemplary cleanliness and linen alignment. Passed with full score.',
    items: [
      { id: 'i1', category: 'Bedroom', name: 'Bed & Headboard', status: 'Pass' },
      { id: 'i2', category: 'Bedroom', name: 'Linen & Duvet', status: 'Pass' },
      { id: 'i3', category: 'Bedroom', name: 'Floor & Carpet', status: 'Pass' },
      { id: 'i4', category: 'Bedroom', name: 'Wardrobe & Hangers', status: 'Pass' },
      { id: 'i5', category: 'Bathroom', name: 'Shower & Tub', status: 'Pass' },
      { id: 'i6', category: 'Bathroom', name: 'Commode & Bidet', status: 'Pass' },
      { id: 'i7', category: 'Bathroom', name: 'Basin & Mirror', status: 'Pass' },
      { id: 'i8', category: 'Bathroom', name: 'Towels & Bath Mat', status: 'Pass' },
      { id: 'i9', category: 'Fixtures & Electronics', name: 'AC & Climate Control', status: 'Pass' },
      { id: 'i10', category: 'Fixtures & Electronics', name: 'Smart TV & Remote', status: 'Pass' },
      { id: 'i11', category: 'Fixtures & Electronics', name: 'Telephone & WiFi Card', status: 'Pass' },
      { id: 'i12', category: 'Fixtures & Electronics', name: 'Mini Bar & Fridge', status: 'Pass' },
      { id: 'i13', category: 'Amenities & Supplies', name: 'Toiletries & Dental Kit', status: 'Pass' },
      { id: 'i14', category: 'Amenities & Supplies', name: 'Tea/Coffee & Mineral Water', status: 'Pass' },
      { id: 'i15', category: 'Overall', name: 'Room Odor & Freshness', status: 'Pass' },
      { id: 'i16', category: 'Overall', name: 'Overall Aesthetics & Safety', status: 'Pass' }
    ],
    createdAt: '2026-09-01T08:25:00.000Z'
  }
];

export const SEED_LOST_FOUND: LostFoundItem[] = [
  {
    id: 'lf-1',
    itemCode: 'LF-2026-0041',
    foundDate: '2026-09-01',
    foundTime: '09:10',
    foundLocation: 'Room 101',
    roomId: 'rm-101',
    roomNumber: '101',
    guestName: 'Tanvir Hossain',
    guestPhone: '+880 1712-998877',
    guestEmail: 'tanvir.h@gmail.com',
    reservationNumber: 'RES-2026-0081',
    checkoutDate: '2026-09-01',
    description: 'Apple iPhone 14 Pro (Space Black) with black leather case',
    category: 'Electronics',
    color: 'Space Black',
    brand: 'Apple',
    condition: 'Excellent',
    foundBy: 'Fatema Begum (Attendant)',
    storedLocation: 'HK Safe Locker A-2',
    storageBinCode: 'BIN-SEC-02',
    isHighValue: true,
    estimatedValue: 145000,
    status: 'Guest Contacted',
    remarks: 'Found on bedside nightstand during checkout cleaning. Front desk phoned guest; guest confirmed and will collect at 4 PM.',
    history: [
      { timestamp: '2026-09-01T09:15:00.000Z', action: 'Item Logged', user: 'Fatema Begum', notes: 'Item discovered during turnover' },
      { timestamp: '2026-09-01T09:20:00.000Z', action: 'Deposited to HK Safe', user: 'Shamsul Huda', notes: 'Locker A-2 sealed' },
      { timestamp: '2026-09-01T09:30:00.000Z', action: 'Guest Contacted', user: 'Front Desk Team', notes: 'Spoke with Tanvir Hossain (+880 1712-998877)' }
    ],
    createdAt: '2026-09-01T09:15:00.000Z'
  },
  {
    id: 'lf-2',
    itemCode: 'LF-2026-0042',
    foundDate: '2026-08-31',
    foundTime: '14:20',
    foundLocation: 'Lobby Lounge & Waiting Area',
    description: 'Men\'s Brown Leather Wallet containing NID card, credit cards & BDT 14,500 cash',
    category: 'Money',
    color: 'Brown',
    brand: 'Apex',
    condition: 'Good',
    foundBy: 'Salma Khatun (Attendant)',
    storedLocation: 'Front Office Safe Box 1',
    storageBinCode: 'BIN-FO-01',
    isHighValue: true,
    estimatedValue: 14500,
    witnessedBy: 'Duty Manager Subrata Roy',
    status: 'Stored',
    remarks: 'Contains NID of Mr. Kamal Chowdhury and cash BDT 14,500 counted and sealed in dual-custody escrow envelope #8812.',
    history: [
      { timestamp: '2026-08-31T14:25:00.000Z', action: 'Item Logged', user: 'Salma Khatun', notes: 'Found under lounge sofa cushion' },
      { timestamp: '2026-08-31T14:35:00.000Z', action: 'Escrow Sealed', user: 'Duty Manager Subrata Roy', notes: 'Dual-custody cash envelope locked in Front Office Safe Box 1' }
    ],
    createdAt: '2026-08-31T14:25:00.000Z'
  },
  {
    id: 'lf-3',
    itemCode: 'LF-2026-0043',
    foundDate: '2026-08-30',
    foundTime: '11:00',
    foundLocation: 'Room 204',
    roomId: 'rm-204',
    roomNumber: '204',
    guestName: 'Sadia Rahman',
    guestPhone: '+880 1819-334455',
    description: 'Gold-plated Ladies Wristwatch in velvet pouch',
    category: 'Jewelry',
    color: 'Gold',
    brand: 'Titan Raga',
    condition: 'Excellent',
    foundBy: 'Rahim Uddin (Attendant)',
    storedLocation: 'HK Safe Locker A-1',
    storageBinCode: 'BIN-SEC-01',
    isHighValue: true,
    estimatedValue: 35000,
    status: 'Returned',
    dispositionMethod: 'Handover In-Person',
    claimedBy: 'Sadia Rahman',
    claimedDate: '2026-08-30T16:30:00.000Z',
    receiverPhone: '+880 1819-334455',
    receiverNid: 'NID-1988267491023',
    returnedBy: 'Shamsul Huda (HK Supervisor)',
    remarks: 'Returned in person after identity & purchase receipt verification.',
    history: [
      { timestamp: '2026-08-30T11:10:00.000Z', action: 'Item Logged', user: 'Rahim Uddin', notes: 'Found in wardrobe top shelf' },
      { timestamp: '2026-08-30T16:30:00.000Z', action: 'Returned & Signed', user: 'Shamsul Huda', notes: 'Handed over to verified owner with photo NID' }
    ],
    createdAt: '2026-08-30T11:10:00.000Z'
  },
  {
    id: 'lf-4',
    itemCode: 'LF-2026-0044',
    foundDate: '2026-08-28',
    foundTime: '17:40',
    foundLocation: 'Swimming Poolside Sunbed #4',
    description: 'Ray-Ban Aviator Sunglasses in brown leather case',
    category: 'Accessories',
    color: 'Gold / Green Lens',
    brand: 'Ray-Ban',
    condition: 'Good',
    foundBy: 'Anisur Rahman (Attendant)',
    storedLocation: 'HK Store Shelf 3',
    storageBinCode: 'BIN-GEN-03',
    isHighValue: false,
    estimatedValue: 12000,
    status: 'Unclaimed',
    remarks: 'Found on pool lounge deck after evening session. No guest name tagged.',
    history: [
      { timestamp: '2026-08-28T17:45:00.000Z', action: 'Item Logged', user: 'Anisur Rahman', notes: 'Logged from pool area' }
    ],
    createdAt: '2026-08-28T17:45:00.000Z'
  },
  {
    id: 'lf-5',
    itemCode: 'LF-2026-0045',
    foundDate: '2026-08-25',
    foundTime: '10:30',
    foundLocation: 'Room 302',
    roomId: 'rm-302',
    roomNumber: '302',
    guestName: 'David K. Miller',
    guestPhone: '+1 415-555-0199',
    guestEmail: 'd.miller@globalconsult.com',
    reservationNumber: 'RES-2026-0065',
    description: 'Lenovo ThinkPad X1 Carbon (14" Black) with USB-C 65W Charger',
    category: 'Electronics',
    color: 'Matte Black',
    brand: 'Lenovo',
    condition: 'Excellent',
    foundBy: 'Fatema Begum (Attendant)',
    storedLocation: 'HK Safe Locker A-2',
    storageBinCode: 'BIN-SEC-02',
    isHighValue: true,
    estimatedValue: 185000,
    witnessedBy: 'Supervisor Shamsul Huda',
    status: 'Returned',
    dispositionMethod: 'Courier Dispatched',
    claimedBy: 'David K. Miller (Guest Authorization)',
    claimedDate: '2026-08-27T15:00:00.000Z',
    receiverPhone: '+1 415-555-0199',
    receiverNid: 'PASSPORT-USA-5829104',
    returnedBy: 'Duty Manager Subrata Roy',
    courierName: 'DHL Express International',
    courierTrackingNumber: 'DHL-EXP-9921448102',
    courierRecipientAddress: 'Global Consulting HQ, Suite 400, Market St, San Francisco, CA 94105, USA',
    courierDispatchDate: '2026-08-27',
    courierCost: 9800,
    remarks: 'Dispatched via DHL Express International with tamper-evident foam packaging. Shipping charge ৳9,800 charged to corporate master card.',
    history: [
      { timestamp: '2026-08-25T10:35:00.000Z', action: 'Item Logged', user: 'Fatema Begum', notes: 'Found inside study desk drawer' },
      { timestamp: '2026-08-25T11:00:00.000Z', action: 'Guest Contacted', user: 'Front Desk', notes: 'Sent international email with serial number verification' },
      { timestamp: '2026-08-27T15:00:00.000Z', action: 'Courier Dispatched', user: 'Subrata Roy', notes: 'DHL Waybill #DHL-EXP-9921448102 issued. Insured transit.' }
    ],
    createdAt: '2026-08-25T10:35:00.000Z'
  },
  {
    id: 'lf-6',
    itemCode: 'LF-2026-0046',
    foundDate: '2026-05-15',
    foundTime: '16:00',
    foundLocation: 'Banquet Grand Ballroom Foyer',
    description: 'Men\'s Navy Wool Blazer (Size 42R) with silk inner lining',
    category: 'Clothing',
    color: 'Navy Blue',
    brand: 'Zara Man',
    condition: 'Good',
    foundBy: 'Mahmudul Hasan (HK Store)',
    storedLocation: 'HK Main Store Shelf 1',
    storageBinCode: 'BIN-STOR-01',
    isHighValue: false,
    estimatedValue: 8500,
    status: 'Unclaimed',
    remarks: 'Exceeded 90 days retention policy (Logged May 15, 2026). Eligible for staff charity raffle or disposal as per Resort SOP.',
    history: [
      { timestamp: '2026-05-15T16:05:00.000Z', action: 'Item Logged', user: 'Mahmudul Hasan', notes: 'Left on coat stand after corporate symposium' },
      { timestamp: '2026-08-15T00:00:00.000Z', action: '90-Day Policy Exceeded', user: 'System', notes: 'Flagged eligible for authorized SOP disposal' }
    ],
    createdAt: '2026-05-15T16:05:00.000Z'
  }
];

export const SEED_LINEN_ITEMS: LinenItem[] = [
  {
    id: 'lin-1',
    itemCode: 'LIN-BS-01',
    name: 'King Bed Sheet (300 TC Cotton Satin)',
    category: 'Bed Sheet',
    sizeOrSpec: '280 x 290 cm',
    uom: 'PCS',
    parLevel: 250,
    totalStock: 240,
    unitCost: 850
  },
  {
    id: 'lin-2',
    itemCode: 'LIN-PC-01',
    name: 'Pillow Case (Cotton Satin White)',
    category: 'Pillow Case',
    sizeOrSpec: '50 x 75 cm',
    uom: 'PCS',
    parLevel: 500,
    totalStock: 480,
    unitCost: 220
  },
  {
    id: 'lin-3',
    itemCode: 'LIN-DC-01',
    name: 'Duvet Cover King (White Stripe)',
    category: 'Duvet Cover',
    sizeOrSpec: '240 x 260 cm',
    uom: 'PCS',
    parLevel: 180,
    totalStock: 175,
    unitCost: 1450
  },
  {
    id: 'lin-4',
    itemCode: 'LIN-BT-01',
    name: 'Bath Towel Plush (650 GSM White)',
    category: 'Bath Towel',
    sizeOrSpec: '70 x 140 cm',
    uom: 'PCS',
    parLevel: 350,
    totalStock: 330,
    unitCost: 480
  },
  {
    id: 'lin-5',
    itemCode: 'LIN-HT-01',
    name: 'Hand Towel (500 GSM White)',
    category: 'Hand Towel',
    sizeOrSpec: '40 x 70 cm',
    uom: 'PCS',
    parLevel: 400,
    totalStock: 390,
    unitCost: 180
  },
  {
    id: 'lin-6',
    itemCode: 'LIN-FT-01',
    name: 'Face Towel / Washcloth',
    category: 'Face Towel',
    sizeOrSpec: '30 x 30 cm',
    uom: 'PCS',
    parLevel: 400,
    totalStock: 385,
    unitCost: 95
  },
  {
    id: 'lin-7',
    itemCode: 'LIN-BM-01',
    name: 'Bath Mat Heavy Duty (800 GSM)',
    category: 'Bath Mat',
    sizeOrSpec: '50 x 80 cm',
    uom: 'PCS',
    parLevel: 200,
    totalStock: 195,
    unitCost: 320
  },
  {
    id: 'lin-8',
    itemCode: 'LIN-PT-01',
    name: 'Pool / Beach Towel (Blue Stripe 600 GSM)',
    category: 'Pool Towel',
    sizeOrSpec: '90 x 180 cm',
    uom: 'PCS',
    parLevel: 220,
    totalStock: 210,
    unitCost: 650
  },
  {
    id: 'lin-9',
    itemCode: 'LIN-TL-01',
    name: 'Banquet Table Cloth (Round 120")',
    category: 'Table Linen',
    sizeOrSpec: '120 inch Diameter',
    uom: 'PCS',
    parLevel: 150,
    totalStock: 140,
    unitCost: 980
  },
  {
    id: 'lin-10',
    itemCode: 'LIN-NP-01',
    name: 'Dinner Napkin (Damask Cotton)',
    category: 'Napkin',
    sizeOrSpec: '50 x 50 cm',
    uom: 'PCS',
    parLevel: 800,
    totalStock: 760,
    unitCost: 75
  }
];

export const SEED_LINEN_STOCKS: LinenLocationStock[] = [
  // Floor 1
  { id: 'ls-1-1', linenItemId: 'lin-1', linenItemName: 'King Bed Sheet', location: 'Floor 1', cleanQty: 30, dirtyQty: 8, inUseQty: 35, inLaundryQty: 0, damagedQty: 1, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },
  { id: 'ls-1-4', linenItemId: 'lin-4', linenItemName: 'Bath Towel Plush', location: 'Floor 1', cleanQty: 45, dirtyQty: 12, inUseQty: 60, inLaundryQty: 0, damagedQty: 0, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },
  
  // Floor 2
  { id: 'ls-2-1', linenItemId: 'lin-1', linenItemName: 'King Bed Sheet', location: 'Floor 2', cleanQty: 25, dirtyQty: 6, inUseQty: 40, inLaundryQty: 0, damagedQty: 0, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },
  { id: 'ls-2-4', linenItemId: 'lin-4', linenItemName: 'Bath Towel Plush', location: 'Floor 2', cleanQty: 40, dirtyQty: 10, inUseQty: 55, inLaundryQty: 0, damagedQty: 1, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },

  // Floor 3
  { id: 'ls-3-1', linenItemId: 'lin-1', linenItemName: 'King Bed Sheet', location: 'Floor 3', cleanQty: 20, dirtyQty: 4, inUseQty: 30, inLaundryQty: 0, damagedQty: 0, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },
  
  // VIP Floor
  { id: 'ls-vip-1', linenItemId: 'lin-1', linenItemName: 'King Bed Sheet', location: 'VIP Floor', cleanQty: 18, dirtyQty: 2, inUseQty: 20, inLaundryQty: 0, damagedQty: 0, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },
  { id: 'ls-vip-3', linenItemId: 'lin-3', linenItemName: 'Duvet Cover King', location: 'VIP Floor', cleanQty: 15, dirtyQty: 2, inUseQty: 15, inLaundryQty: 0, damagedQty: 0, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },

  // Laundry
  { id: 'ls-lau-1', linenItemId: 'lin-1', linenItemName: 'King Bed Sheet', location: 'Laundry', cleanQty: 15, dirtyQty: 0, inUseQty: 0, inLaundryQty: 35, damagedQty: 0, lostQty: 0, lastUpdated: '2026-09-01T09:00:00.000Z' },
  { id: 'ls-lau-4', linenItemId: 'lin-4', linenItemName: 'Bath Towel Plush', location: 'Laundry', cleanQty: 20, dirtyQty: 0, inUseQty: 0, inLaundryQty: 45, damagedQty: 0, lostQty: 0, lastUpdated: '2026-09-01T09:00:00.000Z' },

  // Housekeeping Store (Central Hub)
  { id: 'ls-store-1', linenItemId: 'lin-1', linenItemName: 'King Bed Sheet', location: 'Housekeeping Store', cleanQty: 75, dirtyQty: 0, inUseQty: 0, inLaundryQty: 0, damagedQty: 2, lostQty: 1, lastUpdated: '2026-09-01T08:00:00.000Z' },
  { id: 'ls-store-2', linenItemId: 'lin-2', linenItemName: 'Pillow Case', location: 'Housekeeping Store', cleanQty: 180, dirtyQty: 0, inUseQty: 0, inLaundryQty: 0, damagedQty: 3, lostQty: 2, lastUpdated: '2026-09-01T08:00:00.000Z' },
  { id: 'ls-store-4', linenItemId: 'lin-4', linenItemName: 'Bath Towel Plush', location: 'Housekeeping Store', cleanQty: 110, dirtyQty: 0, inUseQty: 0, inLaundryQty: 0, damagedQty: 1, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' },

  // Pool
  { id: 'ls-pool-8', linenItemId: 'lin-8', linenItemName: 'Pool / Beach Towel', location: 'Pool', cleanQty: 85, dirtyQty: 25, inUseQty: 50, inLaundryQty: 35, damagedQty: 0, lostQty: 1, lastUpdated: '2026-09-01T09:30:00.000Z' },

  // Banquet
  { id: 'ls-banq-9', linenItemId: 'lin-9', linenItemName: 'Banquet Table Cloth', location: 'Banquet', cleanQty: 70, dirtyQty: 15, inUseQty: 40, inLaundryQty: 15, damagedQty: 1, lostQty: 0, lastUpdated: '2026-09-01T08:00:00.000Z' }
];

export const SEED_LINEN_TRANSACTIONS: LinenTransaction[] = [
  {
    id: 'lt-1',
    transactionNumber: 'LIN-TXN-2026-0101',
    date: '2026-09-01',
    time: '08:15',
    transactionType: 'Issue to Floor',
    fromLocation: 'Housekeeping Store',
    toLocation: 'Floor 1',
    linenItemId: 'lin-1',
    linenItemName: 'King Bed Sheet (300 TC Cotton Satin)',
    quantity: 25,
    issuedBy: 'Mahmudul Hasan',
    receivedBy: 'Fatema Begum',
    remarks: 'Daily morning floor pantry replenish',
    createdAt: '2026-09-01T08:15:00.000Z'
  },
  {
    id: 'lt-2',
    transactionNumber: 'LIN-TXN-2026-0102',
    date: '2026-09-01',
    time: '08:30',
    transactionType: 'Send to Laundry',
    fromLocation: 'Floor 1',
    toLocation: 'Laundry',
    linenItemId: 'lin-4',
    linenItemName: 'Bath Towel Plush (650 GSM White)',
    quantity: 35,
    issuedBy: 'Fatema Begum',
    receivedBy: 'Anisur Rahman',
    remarks: 'Morning soiled bath towels sent for washing & steam press',
    createdAt: '2026-09-01T08:30:00.000Z'
  },
  {
    id: 'lt-3',
    transactionNumber: 'LIN-TXN-2026-0103',
    date: '2026-09-01',
    time: '09:00',
    transactionType: 'Receive from Laundry',
    fromLocation: 'Laundry',
    toLocation: 'Housekeeping Store',
    linenItemId: 'lin-1',
    linenItemName: 'King Bed Sheet (300 TC Cotton Satin)',
    quantity: 40,
    issuedBy: 'Anisur Rahman',
    receivedBy: 'Mahmudul Hasan',
    remarks: 'Clean pressed batch received and stacked',
    createdAt: '2026-09-01T09:00:00.000Z'
  }
];

export const SEED_AMENITIES: HousekeepingAmenity[] = [
  {
    id: 'amn-1',
    name: 'Herbal Body Soap (Bar 35g)',
    category: 'Bathroom',
    sku: 'AMN-SP-01',
    unit: 'PCS',
    cost: 18,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 200,
    maximumLevel: 1000,
    currentStock: 480,
    supplier: 'Cosmetics & Toiletries Ltd',
    active: true
  },
  {
    id: 'amn-2',
    name: 'Botanical Shampoo (35ml Bottle)',
    category: 'Bathroom',
    sku: 'AMN-SH-01',
    unit: 'BTL',
    cost: 24,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 250,
    maximumLevel: 1200,
    currentStock: 520,
    supplier: 'Cosmetics & Toiletries Ltd',
    active: true
  },
  {
    id: 'amn-3',
    name: 'Botanical Hair Conditioner (35ml Bottle)',
    category: 'Bathroom',
    sku: 'AMN-HC-01',
    unit: 'BTL',
    cost: 26,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 200,
    maximumLevel: 1000,
    currentStock: 410,
    supplier: 'Cosmetics & Toiletries Ltd',
    active: true
  },
  {
    id: 'amn-4',
    name: 'Eco Bamboo Dental Kit (Brush & Paste)',
    category: 'Bathroom',
    sku: 'AMN-DK-01',
    unit: 'SET',
    cost: 32,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 200,
    maximumLevel: 800,
    currentStock: 390,
    supplier: 'Green Hospitality Supplies',
    active: true
  },
  {
    id: 'amn-5',
    name: 'Biodegradable Shower Cap',
    category: 'Bathroom',
    sku: 'AMN-SC-01',
    unit: 'PCS',
    cost: 12,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 150,
    maximumLevel: 600,
    currentStock: 340,
    supplier: 'Green Hospitality Supplies',
    active: true
  },
  {
    id: 'amn-6',
    name: 'Plush Closed-Toe Slippers (Pair)',
    category: 'Room Comfort',
    sku: 'AMN-SLP-01',
    unit: 'PAIR',
    cost: 48,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 100,
    maximumLevel: 500,
    currentStock: 210,
    supplier: 'Dhaka Hotel Linens Ltd',
    active: true
  },
  {
    id: 'amn-7',
    name: 'Natural Spring Water 500ml (Complimentary)',
    category: 'Beverage',
    sku: 'AMN-WTR-01',
    unit: 'BTL',
    cost: 15,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 300,
    maximumLevel: 2000,
    currentStock: 850,
    supplier: 'Fresh Water Corporation',
    active: true
  },
  {
    id: 'amn-8',
    name: 'Assorted Tea & Coffee Sachet Kit',
    category: 'Beverage',
    sku: 'AMN-TC-01',
    unit: 'SET',
    cost: 28,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 200,
    maximumLevel: 1000,
    currentStock: 490,
    supplier: 'Ispahani Tea Supplies',
    active: true
  },
  {
    id: 'amn-9',
    name: 'Facial Tissue Box (200 Sheets)',
    category: 'Sanitary',
    sku: 'AMN-TIS-01',
    unit: 'BOX',
    cost: 45,
    salePrice: 0,
    isChargeable: false,
    reorderLevel: 100,
    maximumLevel: 500,
    currentStock: 280,
    supplier: 'Bashundhara Paper Mills',
    active: true
  },
  {
    id: 'amn-10',
    name: 'Executive Shaving Kit (Razor & Foam)',
    category: 'Bathroom',
    sku: 'AMN-SHV-01',
    unit: 'SET',
    cost: 65,
    salePrice: 150,
    isChargeable: true,
    reorderLevel: 50,
    maximumLevel: 300,
    currentStock: 140,
    supplier: 'Gillette Bangladesh',
    active: true,
    remarks: 'Chargeable upon extra guest request - billed to Folio'
  },
  {
    id: 'amn-11',
    name: 'Premium Cotton Bath Robe (Resort Monogram)',
    category: 'Room Comfort',
    sku: 'AMN-ROB-01',
    unit: 'PCS',
    cost: 650,
    salePrice: 1200,
    isChargeable: true,
    reorderLevel: 20,
    maximumLevel: 100,
    currentStock: 45,
    supplier: 'Dhaka Hotel Linens Ltd',
    active: true,
    remarks: 'Sold as resort souvenir or chargeable loan'
  }
];

export const SEED_AMENITY_CONSUMPTIONS: AmenityConsumptionRecord[] = [
  {
    id: 'amc-1',
    recordNumber: 'AMC-2026-0801',
    roomId: 'rm-101',
    roomNumber: '101',
    guestName: 'Tanvir Hossain',
    amenityId: 'amn-1',
    amenityName: 'Herbal Body Soap (Bar 35g)',
    quantity: 2,
    unitCost: 18,
    unitPrice: 0,
    totalAmount: 0,
    isChargeable: false,
    isPostedToFolio: false,
    consumedAt: '2026-09-01T09:15:00.000Z',
    attendantName: 'Fatema Begum',
    notes: 'Turnover restock'
  },
  {
    id: 'amc-2',
    recordNumber: 'AMC-2026-0802',
    roomId: 'rm-101',
    roomNumber: '101',
    guestName: 'Tanvir Hossain',
    amenityId: 'amn-2',
    amenityName: 'Botanical Shampoo (35ml Bottle)',
    quantity: 2,
    unitCost: 24,
    unitPrice: 0,
    totalAmount: 0,
    isChargeable: false,
    isPostedToFolio: false,
    consumedAt: '2026-09-01T09:15:00.000Z',
    attendantName: 'Fatema Begum',
    notes: 'Turnover restock'
  },
  {
    id: 'amc-3',
    recordNumber: 'AMC-2026-0803',
    roomId: 'rm-203',
    roomNumber: '203',
    guestName: 'Tariqul Islam',
    amenityId: 'amn-10',
    amenityName: 'Executive Shaving Kit (Razor & Foam)',
    quantity: 1,
    unitCost: 65,
    unitPrice: 150,
    totalAmount: 150,
    isChargeable: true,
    isPostedToFolio: true,
    consumedAt: '2026-09-01T09:20:00.000Z',
    attendantName: 'Rahim Uddin',
    notes: 'Guest requested extra executive kit - posted to Folio'
  }
];

export const SEED_HK_REQUESTS: HousekeepingRequest[] = [
  {
    id: 'hkr-1',
    requestNumber: 'REQ-2026-0031',
    source: 'Guest',
    requestType: 'Extra Towel',
    roomId: 'rm-203',
    roomNumber: '203',
    guestName: 'Tariqul Islam',
    guestPhone: '+880 1711-889900',
    priority: 'High',
    status: 'In Progress',
    assignedTo: 'hks-2',
    assignedAttendantName: 'Rahim Uddin',
    isChargeable: false,
    isPostedToFolio: false,
    requestedAt: '2026-09-01T09:10:00.000Z',
    requestedBy: 'Front Desk (Intercom Call)',
    notes: '2 extra large bath towels requested for pool swim.'
  },
  {
    id: 'hkr-2',
    requestNumber: 'REQ-2026-0032',
    source: 'Front Desk',
    requestType: 'Baby Cot',
    roomId: 'rm-305',
    roomNumber: '305',
    guestName: 'Mahbubur Rahman (VIP)',
    priority: 'VIP',
    status: 'Assigned',
    assignedTo: 'hks-4',
    assignedAttendantName: 'Jannat Ara',
    isChargeable: false,
    isPostedToFolio: false,
    requestedAt: '2026-09-01T09:25:00.000Z',
    requestedBy: 'Front Desk Manager',
    notes: 'VIP guest with infant checking in at 3 PM. Baby cot with sterile bedding setup required.'
  },
  {
    id: 'hkr-3',
    requestNumber: 'REQ-2026-0033',
    source: 'Guest',
    requestType: 'Water',
    roomId: 'rm-102',
    roomNumber: '102',
    guestName: 'Farhana Ahmed',
    priority: 'Normal',
    status: 'Completed',
    assignedTo: 'hks-1',
    assignedAttendantName: 'Fatema Begum',
    isChargeable: false,
    isPostedToFolio: false,
    requestedAt: '2026-09-01T08:40:00.000Z',
    completedAt: '2026-09-01T08:50:00.000Z',
    requestedBy: 'Direct Guest App Call',
    completedBy: 'Fatema Begum',
    notes: 'Delivered 2 chilled 500ml mineral water bottles.'
  },
  {
    id: 'hkr-4',
    requestNumber: 'REQ-2026-0034',
    source: 'Guest',
    requestType: 'Iron',
    roomId: 'rm-104',
    roomNumber: '104',
    guestName: 'Anwar Sadat',
    priority: 'Normal',
    status: 'New',
    isChargeable: false,
    isPostedToFolio: false,
    requestedAt: '2026-09-01T09:45:00.000Z',
    requestedBy: 'Front Desk Operator',
    notes: 'Steam iron and foldable ironing board requested.'
  }
];

export const SEED_DISCREPANCIES: RoomDiscrepancyRecord[] = [
  {
    id: 'disc-1',
    roomId: 'rm-106',
    roomNumber: '106',
    frontOfficeStatus: 'Vacant',
    housekeepingStatus: 'Occupied',
    frontOfficeDetails: 'FO System shows checked out / no active folio',
    housekeepingDetails: 'HK Attendant found guest luggage and clothing inside room',
    detectedAt: '2026-09-01T08:45:00.000Z',
    reportedBy: 'Fatema Begum (Attendant)',
    status: 'Open',
    resolutionNotes: 'Supervisor investigating with Front Desk for possible late checkout extension.'
  }
];

export const SEED_HK_SHIFTS: HousekeepingShiftRecord[] = [
  {
    id: 'hksf-1',
    shiftName: 'Morning Shift',
    shiftDate: '2026-09-01',
    staffId: 'hks-1',
    staffName: 'Fatema Begum',
    startTime: '07:00',
    assignedRoomsCount: 6,
    completedRoomsCount: 4,
    rejectedCount: 0,
    pendingCount: 2,
    avgCleaningTimeMinutes: 28,
    status: 'Active'
  },
  {
    id: 'hksf-2',
    shiftName: 'Morning Shift',
    shiftDate: '2026-09-01',
    staffId: 'hks-2',
    staffName: 'Rahim Uddin',
    startTime: '07:00',
    assignedRoomsCount: 5,
    completedRoomsCount: 3,
    rejectedCount: 0,
    pendingCount: 2,
    avgCleaningTimeMinutes: 32,
    status: 'Active'
  },
  {
    id: 'hksf-3',
    shiftName: 'Morning Shift',
    shiftDate: '2026-09-01',
    staffId: 'hks-3',
    staffName: 'Salma Khatun',
    startTime: '07:00',
    assignedRoomsCount: 6,
    completedRoomsCount: 5,
    rejectedCount: 1,
    pendingCount: 1,
    avgCleaningTimeMinutes: 26,
    status: 'Active'
  }
];
