import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas-pro';
import { ReportQueryResult } from './reportingService';
import { pmsService } from './pmsService';
import { Invoice, Folio, Payment, Reservation, Stay, EventBooking, BanquetQuotation } from '../types/pms';

export interface DocumentExportData {
  title: string;
  subtitle?: string;
  documentType?: string;
  referenceNumber?: string;
  date?: string;
  metadata?: Record<string, string | number | undefined>;
  columns: { key: string; header: string; align?: string }[];
  rows: Record<string, any>[];
  summaryTotals?: Record<string, any>;
  footerNotes?: string[];
  department?: string;
  logoUrl?: string;
  propertyName?: string;
}

/**
 * Sanitizes strings for standard jsPDF Helvetica core fonts.
 * Replaces non-ASCII Unicode glyphs (e.g. ৳, •, —, smart quotes) that crash standard jsPDF encoding.
 */
export function cleanPdfText(val: any): string {
  if (val === undefined || val === null) return '';
  let s = String(val)
    .replace(/৳/g, 'BDT ')
    .replace(/•/g, '|')
    .replace(/[—–]/g, '-')
    .replace(/…/g, '...')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u00A0]/g, ' ');
  try {
    s = s.normalize('NFKD').replace(/[^\x20-\x7E\r\n\t]/g, '');
  } catch {
    s = s.replace(/[^\x20-\x7E\r\n\t]/g, '');
  }
  return s.trim();
}

/**
 * Renders the property brand logo in the PDF document header.
 * - If a custom image logo (DataURL, PNG, JPEG) is configured, it renders inside a crisp white frame.
 * - If no custom image is configured, it renders an elegant vector property crest/monogram badge with the resort initials and gold styling, ensuring 100% of all generated PDFs always display a high-end property logo.
 */
export function renderPdfPropertyLogo(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  logoUrl?: string,
  propertyName?: string
): void {
  if (logoUrl && typeof logoUrl === 'string' && logoUrl.trim().length > 0) {
    try {
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(x, y, w, h, 1, 1, 'F');
      const isPng = logoUrl.startsWith('data:image/png');
      const isJpeg = logoUrl.startsWith('data:image/jpeg') || logoUrl.startsWith('data:image/jpg');
      const fmt = isPng ? 'PNG' : isJpeg ? 'JPEG' : undefined;
      doc.addImage(logoUrl, fmt || 'PNG', x + 1, y + 1, w - 2, h - 2);
      return;
    } catch {
      try {
        doc.addImage(logoUrl, 'JPEG', x + 1, y + 1, w - 2, h - 2);
        return;
      } catch (e) {
        // Fall through to fallback vector crest
      }
    }
  }

  // Fallback: Crisp, prestigious hotel & resort vector crest
  doc.setFillColor(30, 41, 59); // slate-800
  doc.setDrawColor(245, 158, 11); // amber-500
  doc.roundedRect(x, y, w, h, 1.2, 1.2, 'FD');

  // Inner gold border accent
  doc.setDrawColor(217, 119, 6);
  doc.roundedRect(x + 0.8, y + 0.8, w - 1.6, h - 1.6, 0.8, 0.8, 'D');

  const pName = propertyName || pmsService.getState()?.settings?.resortName || 'LESync';
  const words = pName.trim().split(/\s+/);
  const initials = words.length >= 2
    ? (words[0][0] + words[1][0]).toUpperCase()
    : pName.slice(0, 2).toUpperCase();

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(Math.min(9, h * 0.46));
  doc.setTextColor(253, 224, 71); // bright gold/yellow
  doc.text(initials, x + w / 2, y + h * 0.54, { align: 'center' });

  doc.setFontSize(Math.max(4, h * 0.22));
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(226, 232, 240);
  doc.text('RESORT', x + w / 2, y + h * 0.84, { align: 'center' });
}

/**
 * Standard PDF Document Metadata interface
 */
export interface PdfMetadataOptions {
  title?: string;
  subject?: string;
  author?: string;
  creator?: string;
  keywords?: string;
}

/**
 * Applies standard PDF metadata (Document Title, Subject, Author, Creator, Generation Timestamp)
 * to ensure PDF viewers (Adobe Acrobat, Chrome PDF Viewer, Apple Preview, Firefox, etc.)
 * correctly index, title, and display the document header and file properties.
 */
export function applyPdfMetadata(
  doc: jsPDF,
  options?: PdfMetadataOptions | string,
  propertyName?: string
): void {
  try {
    const resortName = propertyName || pmsService.getState()?.settings?.resortName || 'LESync PMS';
    const title = typeof options === 'string'
      ? options
      : options?.title || 'Official Property Management Record';
    const subject = typeof options === 'object' && options?.subject
      ? options.subject
      : `Official record generated by ${resortName}`;
    const author = typeof options === 'object' && options?.author
      ? options.author
      : resortName;
    const creator = typeof options === 'object' && options?.creator
      ? options.creator
      : `${resortName} - LESync Enterprise PMS`;
    const keywords = typeof options === 'object' && options?.keywords
      ? options.keywords
      : 'LESync, PMS, Hotel, Resort, Billing, Reservation, Invoice, Audit';

    const cleanTitle = cleanPdfText(title);
    const cleanSubject = cleanPdfText(subject);
    const cleanAuthor = cleanPdfText(author);
    const cleanCreator = cleanPdfText(creator);
    const cleanKeywords = cleanPdfText(keywords);

    const properties: Record<string, any> = {
      title: cleanTitle,
      subject: cleanSubject,
      author: cleanAuthor,
      creator: cleanCreator,
      keywords: cleanKeywords
    };

    if (typeof (doc as any).setDocumentProperties === 'function') {
      (doc as any).setDocumentProperties(properties);
    } else if (typeof (doc as any).setProperties === 'function') {
      (doc as any).setProperties(properties);
    }
  } catch (err) {
    console.warn('Non-blocking warning: failed to apply PDF metadata:', err);
  }
}

/**
 * Universal, rock-solid PDF download helper.
 * Completely replaces fragile doc.save() / FileSaver.js which corrupts or blocks downloads
 * inside iframes, sandbox containers, and strict Content-Security-Policy web apps.
 * Automatically injects standard document metadata (title, author, timestamp, creator)
 * and creates a standard Blob to trigger download via HTML5 anchor tag.
 */
export function triggerPdfDownload(
  doc: jsPDF,
  filename: string,
  metadata?: PdfMetadataOptions | string
): boolean {
  try {
    const cleanFilename = cleanPdfText(filename.toLowerCase().endsWith('.pdf') ? filename : `${filename}.pdf`).replace(/\s+/g, '_');
    
    // Automatically apply proper PDF document metadata if not already explicitly set
    const fallbackTitle = cleanFilename.replace(/\.pdf$/i, '').replace(/_/g, ' ');
    const metaOptions: PdfMetadataOptions = typeof metadata === 'string'
      ? { title: metadata }
      : { title: fallbackTitle, ...metadata };
    applyPdfMetadata(doc, metaOptions);

    // Generate valid application/pdf Blob directly from the jsPDF instance
    const blob: Blob = doc.output('blob');
    if (!blob || blob.size === 0) {
      console.warn('doc.output("blob") returned empty blob, falling back to arraybuffer');
      const arrayBuffer = doc.output('arraybuffer');
      const fallbackBlob = new Blob([arrayBuffer], { type: 'application/pdf' });
      return triggerBlobDownload(fallbackBlob, cleanFilename);
    }
    return triggerBlobDownload(blob, cleanFilename);
  } catch (err) {
    console.error('Failed to export PDF blob:', err);
    try {
      // Last-ditch fallback
      const cleanFilename = cleanPdfText(filename.toLowerCase().endsWith('.pdf') ? filename : `${filename}.pdf`).replace(/\s+/g, '_');
      doc.save(cleanFilename);
      return true;
    } catch (saveErr) {
      console.error('Critical: doc.save fallback also failed:', saveErr);
      return false;
    }
  }
}

/**
 * Helper to download any PDF Blob via standard DOM anchor click
 */
export function triggerBlobDownload(blob: Blob, filename: string): boolean {
  if (typeof window === 'undefined') return false;
  try {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';
    link.rel = 'noopener';
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      try {
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      } catch {
        // Ignored
      }
    }, 2000);
    return true;
  } catch (e) {
    console.error('Blob link click failed:', e);
    return false;
  }
}

export interface ExportElementOptions {
  isThermal?: boolean;
  isLandscape?: boolean;
  scale?: number;
  metadata?: PdfMetadataOptions;
  margin?: number;
}

/**
 * High-fidelity PDF exporter that captures any DOM element (e.g. In-app document preview)
 * using html2canvas-pro at high DPI and generates an exact 1:1 replica PDF.
 * Supports:
 * - Exact WYSIWYG matching of in-app document previews
 * - 80mm continuous thermal receipt rolls for POS bills & KOT slips
 * - Clean multi-page pagination for long folios, invoices, and reports
 * - Proper document metadata and resilient browser downloads
 */
export async function exportElementToPDF(
  element: HTMLElement,
  filename: string,
  options?: ExportElementOptions
): Promise<boolean> {
  if (!element || typeof window === 'undefined') return false;

  const scrollParent = element.parentElement;
  const prevScrollTop = scrollParent ? scrollParent.scrollTop : 0;
  const prevScrollLeft = scrollParent ? scrollParent.scrollLeft : 0;

  try {
    if (scrollParent) {
      scrollParent.scrollTop = 0;
      scrollParent.scrollLeft = 0;
    }

    const isThermal = options?.isThermal ?? false;
    const isLandscape = options?.isLandscape ?? false;
    const scale = options?.scale ?? 3; // Crisp 3x retina density for 300+ DPI

    // Capture element with html2canvas-pro
    const canvas = await html2canvas(element, {
      scale: scale,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      logging: false,
      scrollX: 0,
      scrollY: 0,
      width: element.offsetWidth,
      height: element.offsetHeight,
      windowWidth: document.documentElement.offsetWidth,
      windowHeight: document.documentElement.offsetHeight,
      ignoreElements: (el: Element) => {
        return (
          el.classList?.contains('no-print') ||
          el.classList?.contains('print:hidden') ||
          el.getAttribute?.('data-no-print') === 'true'
        );
      }
    });

    if (!canvas || canvas.width === 0 || canvas.height === 0) {
      console.warn('Canvas capture produced empty canvas');
      return false;
    }

    if (isThermal) {
      // 80mm continuous thermal slip roll (POS Bill & KOT Receipt)
      const rollWidthMm = 80;
      const marginMm = options?.margin ?? 2;
      const contentWidthMm = rollWidthMm - marginMm * 2;
      const contentHeightMm = (canvas.height * contentWidthMm) / canvas.width;
      const rollHeightMm = Math.max(60, Math.ceil(contentHeightMm + marginMm * 2));

      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: [rollWidthMm, rollHeightMm]
      });

      const imgData = canvas.toDataURL('image/png');
      doc.addImage(imgData, 'PNG', marginMm, marginMm, contentWidthMm, contentHeightMm, undefined, 'FAST');
      return triggerPdfDownload(doc, filename, options?.metadata);
    }

    // Standard A4 document (Portrait 210x297mm or Landscape 297x210mm)
    const pageWidthMm = isLandscape ? 297 : 210;
    const pageHeightMm = isLandscape ? 210 : 297;
    const marginMm = options?.margin ?? 6;
    const contentWidthMm = pageWidthMm - marginMm * 2;
    const maxPageContentHeightMm = pageHeightMm - marginMm * 2;
    const totalHeightMm = (canvas.height * contentWidthMm) / canvas.width;

    const doc = new jsPDF({
      orientation: isLandscape ? 'landscape' : 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    if (totalHeightMm <= maxPageContentHeightMm + 2) {
      // Single page document with lossless PNG
      const imgData = canvas.toDataURL('image/png');
      doc.addImage(imgData, 'PNG', marginMm, marginMm, contentWidthMm, totalHeightMm, undefined, 'FAST');
    } else if (totalHeightMm <= maxPageContentHeightMm * 1.15) {
      // Fit slightly taller voucher cards seamlessly onto single page without clipping or spilling
      const fittedWidthMm = (contentWidthMm * maxPageContentHeightMm) / totalHeightMm;
      const fittedLeftMm = marginMm + (contentWidthMm - fittedWidthMm) / 2;
      const imgData = canvas.toDataURL('image/png');
      doc.addImage(imgData, 'PNG', fittedLeftMm, marginMm, fittedWidthMm, maxPageContentHeightMm, undefined, 'FAST');
    } else {
      // Multi-page document with clean page-by-page slicing
      const pxPerMm = canvas.width / contentWidthMm;
      const pageSlicePx = Math.floor(maxPageContentHeightMm * pxPerMm);
      let yOffsetPx = 0;
      let pageIndex = 0;

      while (yOffsetPx < canvas.height) {
        const currentSlicePx = Math.min(pageSlicePx, canvas.height - yOffsetPx);
        const pageCanvas = document.createElement('canvas');
        pageCanvas.width = canvas.width;
        pageCanvas.height = currentSlicePx;
        const ctx = pageCanvas.getContext('2d');
        if (ctx) {
          ctx.fillStyle = '#ffffff';
          ctx.fillRect(0, 0, pageCanvas.width, pageCanvas.height);
          ctx.drawImage(
            canvas,
            0, yOffsetPx, canvas.width, currentSlicePx,
            0, 0, canvas.width, currentSlicePx
          );
        }

        if (pageIndex > 0) {
          doc.addPage('a4', isLandscape ? 'landscape' : 'portrait');
        }

        const sliceImgData = pageCanvas.toDataURL('image/png');
        const sliceHeightMm = (currentSlicePx * contentWidthMm) / canvas.width;
        doc.addImage(sliceImgData, 'PNG', marginMm, marginMm, contentWidthMm, sliceHeightMm, undefined, 'FAST');

        yOffsetPx += currentSlicePx;
        pageIndex++;
      }
    }

    return triggerPdfDownload(doc, filename, options?.metadata);
  } catch (err) {
    console.error('exportElementToPDF error:', err);
    return false;
  } finally {
    if (scrollParent) {
      scrollParent.scrollTop = prevScrollTop;
      scrollParent.scrollLeft = prevScrollLeft;
    }
  }
}

export const pdfExportService = {
  /**
   * Export exact HTML DOM preview element to high-res PDF
   */
  exportElementToPDF(
    element: HTMLElement,
    filename: string,
    options?: ExportElementOptions
  ): Promise<boolean> {
    return exportElementToPDF(element, filename, options);
  },
  /**
   * Generates and downloads a clean, professional, multi-page vector PDF for reports and bills.
   * Completely resilient against Unicode font crashes and dynamic table sizes.
   */
  exportToPDF(data: DocumentExportData, filename: string): boolean {
    try {
      const columns: { key: string; header: string; align?: string }[] = (data.columns && data.columns.length > 0)
        ? data.columns
        : (data.rows && data.rows.length > 0)
          ? Object.keys(data.rows[0]).map(k => ({ key: k, header: k, align: 'left' }))
          : [{ key: 'info', header: 'Details', align: 'left' }];

      const isLandscape = columns.length > 5;
      const doc = new jsPDF({
        orientation: isLandscape ? 'landscape' : 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 10;
      const contentWidth = pageWidth - margin * 2;
      let y = margin;

      const drawHeader = (isFirstPage: boolean) => {
        const sysSettings = pmsService.getState()?.settings;
        const liveResortName = data.propertyName || sysSettings?.resortName || 'Hotel & Resort PMS';
        const logo = data.logoUrl || sysSettings?.logoUrl;
        const headerHeight = 22;

        // Top header band
        doc.setFillColor(15, 23, 42); // slate-900
        doc.roundedRect(margin, y, contentWidth, headerHeight, 1.5, 1.5, 'F');

        // Render Property Logo on left (Upload image or elegant vector monogram crest)
        const logoWidth = 24;
        const logoHeight = 16;
        const logoX = margin + 3.5;
        const logoY = y + 3;
        renderPdfPropertyLogo(doc, logoX, logoY, logoWidth, logoHeight, logo, liveResortName);

        // Text start column after logo
        const textStartX = logoX + logoWidth + 4.5;

        // 1. Property Name in Amber Gold (Prominent Heading)
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(245, 158, 11); // amber-500
        const pNameStr = cleanPdfText(liveResortName.toUpperCase());
        const maxPNameLength = isLandscape ? 65 : 45;
        const pNameTrunc = pNameStr.length > maxPNameLength ? pNameStr.substring(0, maxPNameLength - 2) + '...' : pNameStr;
        doc.text(pNameTrunc, textStartX, y + 6.5);

        // 2. Document Title in Bold White
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10.5);
        doc.setTextColor(255, 255, 255);
        const titleStr = cleanPdfText(data.title.toUpperCase());
        const maxTitleLength = isLandscape ? 60 : 38;
        const titleTrunc = titleStr.length > maxTitleLength ? titleStr.substring(0, maxTitleLength - 2) + '...' : titleStr;
        doc.text(titleTrunc, textStartX, y + 12);

        // 3. Subtitle / Department / Contact details
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6.5);
        doc.setTextColor(148, 163, 184); // slate-400
        const contactLine = [sysSettings?.phone, sysSettings?.email, sysSettings?.website].filter(Boolean).join(' | ');
        const subText = data.subtitle || (contactLine ? `${contactLine} • OFFICIAL MIS RECORD` : `${liveResortName} • OFFICIAL RECORD`);
        const subTrunc = cleanPdfText(subText);
        const maxSubLength = isLandscape ? 80 : 50;
        doc.text(subTrunc.length > maxSubLength ? subTrunc.substring(0, maxSubLength - 2) + '...' : subTrunc, textStartX, y + 17.5);

        // Right side badge: Reference Number & Date
        const rightBoxWidth = isLandscape ? 56 : 48;
        const rightBoxX = margin + contentWidth - rightBoxWidth - 3;
        doc.setFillColor(30, 41, 59); // slate-800
        doc.roundedRect(rightBoxX, y + 3, rightBoxWidth, 16, 1, 1, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6.5);
        doc.setTextColor(203, 213, 225);
        const refLabel = data.referenceNumber ? 'REF / SERIAL #:' : 'DOCUMENT STATUS:';
        doc.text(refLabel, rightBoxX + 2.5, y + 7.2);

        doc.setFontSize(7.5);
        doc.setTextColor(253, 224, 71); // yellow-300
        const refVal = cleanPdfText(data.referenceNumber || 'SYSTEM CERTIFIED');
        doc.text(refVal.length > 20 ? refVal.substring(0, 18) + '..' : refVal, rightBoxX + 2.5, y + 11.5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6);
        doc.setTextColor(148, 163, 184);
        doc.text(`Date: ${cleanPdfText(data.date || new Date().toLocaleDateString('en-GB'))}`, rightBoxX + 2.5, y + 15.5);

        y += headerHeight + 3;

        // Metadata Key-Value row if on first page
        if (isFirstPage && data.metadata && Object.keys(data.metadata).length > 0) {
          doc.setFillColor(248, 250, 252); // slate-50
          doc.setDrawColor(226, 232, 240); // slate-200
          const metaEntries = Object.entries(data.metadata).filter(([_, v]) => v !== undefined && v !== '');
          const colsPerRow = isLandscape ? 4 : 3;
          const metaHeight = Math.ceil(metaEntries.length / colsPerRow) * 6 + 4;
          doc.roundedRect(margin, y, contentWidth, metaHeight, 1, 1, 'FD');

          doc.setFontSize(7);
          metaEntries.forEach(([key, val], idx) => {
            const colIndex = idx % colsPerRow;
            const rowIndex = Math.floor(idx / colsPerRow);
            const colWidth = contentWidth / colsPerRow;
            const xPos = margin + 3 + colIndex * colWidth;
            const yPos = y + 5 + rowIndex * 6;

            doc.setFont('helvetica', 'normal');
            doc.setTextColor(100, 116, 139);
            doc.text(`${cleanPdfText(key)}:`, xPos, yPos);

            doc.setFont('helvetica', 'bold');
            doc.setTextColor(15, 23, 42);
            const valStr = cleanPdfText(val);
            const truncated = valStr.length > 25 ? valStr.substring(0, 23) + '...' : valStr;
            doc.text(truncated, xPos + 22, yPos);
          });

          y += metaHeight + 4;
        }
      };

      // Calculate column widths based on weights
      const totalCols = columns.length;
      const colWidths: number[] = [];
      const standardWidth = contentWidth / totalCols;

      for (let i = 0; i < totalCols; i++) {
        const col = columns[i];
        const keyLower = col.key.toLowerCase();
        if (keyLower === 'id' || keyLower === 'code' || keyLower === 'roomnumber' || keyLower === 'status' || keyLower === 'qty') {
          colWidths.push(Math.max(16, standardWidth * 0.75));
        } else if (keyLower.includes('description') || keyLower.includes('name') || keyLower.includes('title')) {
          colWidths.push(standardWidth * 1.4);
        } else {
          colWidths.push(standardWidth);
        }
      }

      // Normalize colWidths to exactly fill contentWidth
      const sumWidths = colWidths.reduce((a, b) => a + b, 0);
      const scaleFactor = contentWidth / sumWidths;
      for (let i = 0; i < colWidths.length; i++) {
        colWidths[i] = colWidths[i] * scaleFactor;
      }

      drawHeader(true);

      const drawTableHeader = () => {
        doc.setFillColor(241, 245, 249); // slate-100
        doc.setDrawColor(203, 213, 225); // slate-300
        doc.rect(margin, y, contentWidth, 7, 'FD');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(30, 41, 59);

        let currentX = margin;
        columns.forEach((col, idx) => {
          const w = colWidths[idx];
          const align = col.align === 'right' ? 'right' : col.align === 'center' ? 'center' : 'left';
          const textX = align === 'right' ? currentX + w - 2 : align === 'center' ? currentX + w / 2 : currentX + 2;
          doc.text(cleanPdfText(col.header.toUpperCase()), textX, y + 4.5, { align });
          currentX += w;
        });

        y += 7;
      };

      drawTableHeader();

      // Render Table Rows
      const rows = data.rows || [];
      rows.forEach((row, rIdx) => {
        if (y > pageHeight - 24) {
          doc.addPage();
          y = margin;
          drawHeader(false);
          drawTableHeader();
        }

        const isEven = rIdx % 2 === 1;
        if (isEven) {
          doc.setFillColor(248, 250, 252);
          doc.rect(margin, y, contentWidth, 6, 'F');
        }

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(15, 23, 42);

        let currentX = margin;
        columns.forEach((col, idx) => {
          const w = colWidths[idx];
          const rawVal = row[col.key];
          let valStr = rawVal !== undefined && rawVal !== null ? String(rawVal) : '-';
          if (typeof rawVal === 'number' && (col.key.toLowerCase().includes('total') || col.key.toLowerCase().includes('amount') || col.key.toLowerCase().includes('rate') || col.key.toLowerCase().includes('price') || col.key.toLowerCase().includes('revenue') || col.key.toLowerCase().includes('balance'))) {
            valStr = `BDT ${rawVal.toLocaleString()}`;
          }

          valStr = cleanPdfText(valStr);

          const align = col.align === 'right' ? 'right' : col.align === 'center' ? 'center' : 'left';
          const textX = align === 'right' ? currentX + w - 2 : align === 'center' ? currentX + w / 2 : currentX + 2;

          const maxChars = Math.floor(w / 1.7);
          if (valStr.length > maxChars) {
            valStr = valStr.substring(0, Math.max(1, maxChars - 1)) + '...';
          }

          doc.text(valStr, textX, y + 4.2, { align });
          currentX += w;
        });

        doc.setDrawColor(241, 245, 249);
        doc.line(margin, y + 6, margin + contentWidth, y + 6);

        y += 6;
      });

      // Summary Totals Row (if provided)
      if (data.summaryTotals && Object.keys(data.summaryTotals).length > 0) {
        if (y > pageHeight - 35) {
          doc.addPage();
          y = margin;
          drawHeader(false);
        }

        doc.setFillColor(241, 245, 249);
        doc.setDrawColor(15, 23, 42);
        doc.rect(margin, y, contentWidth, 7, 'FD');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(15, 23, 42);

        let currentX = margin;
        columns.forEach((col, idx) => {
          const w = colWidths[idx];
          const totalVal = data.summaryTotals![col.key];
          let valStr = totalVal !== undefined && totalVal !== null ? String(totalVal) : '';
          if (typeof totalVal === 'number') {
            valStr = `BDT ${totalVal.toLocaleString()}`;
          } else if (idx === 0 && !valStr) {
            valStr = 'AUDITED TOTALS:';
          }

          valStr = cleanPdfText(valStr);

          const align = col.align === 'right' ? 'right' : col.align === 'center' ? 'center' : 'left';
          const textX = align === 'right' ? currentX + w - 2 : align === 'center' ? currentX + w / 2 : currentX + 2;
          doc.text(valStr, textX, y + 4.8, { align });
          currentX += w;
        });

        y += 9;
      }

      // Executive Verification & Signatures on final page
      if (y < pageHeight - 22) {
        y = Math.max(y + 6, pageHeight - 22);
        doc.setDrawColor(203, 213, 225);
        doc.line(margin, y, margin + contentWidth, y);

        const sigWidth = contentWidth / 3;
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(71, 85, 105);

        doc.text('Prepared By: Front Desk / Cashier', margin + 2, y + 5);
        doc.text('Audited By: Financial Controller / Audit', margin + sigWidth + 2, y + 5);
        doc.text('Approved: General Manager / Director', margin + sigWidth * 2 + 2, y + 5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6);
        doc.setTextColor(148, 163, 184);
        doc.text('Certified Audited Document • Official PMS MIS Record', margin + 2, y + 9);
        doc.text('Confidential & Proprietary Records', margin + sigWidth * 2 + 2, y + 9);
      }

      // Accurate Page Numbering Stamp pass across all generated pages
      const totalPages = doc.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(203, 213, 225);
        doc.text(`Page ${p} of ${totalPages}`, pageWidth - margin - 4, margin + 6.5, { align: 'right' });
      }

      const cleanFilename = cleanPdfText(filename.toLowerCase().endsWith('.pdf') ? filename : `${filename}.pdf`).replace(/\s+/g, '_');
      return triggerPdfDownload(doc, cleanFilename, {
        title: data.title,
        subject: data.subtitle || `${data.title} - ${data.propertyName || 'LESync PMS'}`,
        author: data.propertyName || 'LESync Property Management System',
        creator: `${data.propertyName || 'LESync'} - Enterprise PMS Export Engine`,
        keywords: `${data.title}, Report, Audit, LESync, PMS, Finance`
      });
    } catch (err) {
      console.error('Failed to generate vector PDF report:', err);
      return false;
    }
  },

  /**
   * Export any standard ReportQueryResult directly to PDF
   */
  exportReportResultToPDF(result: ReportQueryResult, customFileName?: string): boolean {
    const sysSettings = pmsService.getState()?.settings;
    const propertyName = sysSettings?.resortName || 'Hotel & Resort PMS';
    const reportCode = result.definition?.reportCode || 'REPORT';
    const filename = customFileName || `${reportCode}_${new Date().toISOString().split('T')[0]}.pdf`;

    return this.exportToPDF({
      title: result.definition?.reportName || 'AUDITED REPORT',
      subtitle: `${propertyName.toUpperCase()} • OFFICIAL AUDITED REPORT`,
      date: result.generatedAt || new Date().toLocaleString(),
      columns: result.columns.map(c => ({ key: c.key, header: c.header, align: c.align })),
      rows: result.rows || [],
      summaryTotals: result.summaryTotals,
      department: result.department || 'Property Operations',
      propertyName,
      logoUrl: sysSettings?.logoUrl,
      metadata: {
        'Audited By': result.generatedBy || 'System Auditor',
        'Scope': result.definition?.defaultDataScope || 'Consolidated Property',
        'Category': result.definition?.category || 'Management'
      }
    }, filename);
  },

  /**
   * Export Tax Invoice to PDF
   */
  exportInvoiceToPDF(invoice: Invoice, propertyName?: string): boolean {
    const sysSettings = pmsService.getState()?.settings;
    const resortName = propertyName || sysSettings?.resortName || 'Hotel & Resort PMS';
    const filename = `Invoice_${invoice.invoiceNumber || 'INV'}.pdf`;

    return this.exportToPDF({
      title: `TAX INVOICE - ${invoice.invoiceNumber}`,
      subtitle: `${resortName.toUpperCase()} • OFFICIAL TAX INVOICE & BILL`,
      referenceNumber: invoice.invoiceNumber,
      date: invoice.dates || new Date().toISOString().split('T')[0],
      propertyName: resortName,
      logoUrl: sysSettings?.logoUrl,
      columns: [
        { key: 'description', header: 'Item Description' },
        { key: 'quantity', header: 'Qty', align: 'center' },
        { key: 'unitPrice', header: 'Unit Price (BDT)', align: 'right' },
        { key: 'total', header: 'Total (BDT)', align: 'right' }
      ],
      rows: invoice.items || [],
      summaryTotals: {
        description: 'Total Amount Due',
        total: invoice.grandTotal
      },
      metadata: {
        'Billed To': invoice.guestOrClientName,
        'Room / Hall': invoice.roomOrHall,
        'Subtotal': `BDT ${(invoice.subtotal || 0).toLocaleString()}`,
        'VAT / Tax': `BDT ${(invoice.tax || 0).toLocaleString()}`,
        'Service Charge': `BDT ${(invoice.serviceCharge || 0).toLocaleString()}`,
        'Grand Total': `BDT ${(invoice.grandTotal || 0).toLocaleString()}`,
        'Paid Amount': `BDT ${(invoice.paidAmount || 0).toLocaleString()}`,
        'Balance Due': `BDT ${(invoice.balance || 0).toLocaleString()}`
      },
      footerNotes: [
        'All bills are payable upon receipt or before check-out.',
        `Official Billing System • ${resortName}`
      ]
    }, filename);
  },

  /**
   * Export POS Order / 80mm KOT Receipt to PDF
   */
  exportPosOrderToPDF(order: any, isKot: boolean = false, propertyName?: string): boolean {
    const sysSettings = pmsService.getState()?.settings;
    const resortName = propertyName || sysSettings?.resortName || 'LESync Resort & Spa';
    const outlet = order.outlet === 'bar' ? 'Bar & Sky Lounge' : 'Restaurant & In-Room Dining';
    const filename = `${isKot ? 'KOT' : 'POS_Receipt'}_${order.orderNumber || 'ORD'}.pdf`;

    if (isKot) {
      return this.exportToPDF({
        title: `KITCHEN ORDER TICKET (KOT) - ${order.orderNumber}`,
        subtitle: `${resortName.toUpperCase()} • ${outlet.toUpperCase()}`,
        referenceNumber: `KOT-${order.orderNumber}`,
        date: order.createdAt || new Date().toISOString(),
        propertyName: resortName,
        logoUrl: sysSettings?.logoUrl,
        columns: [
          { key: 'name', header: 'Item to Prepare' },
          { key: 'quantity', header: 'Quantity', align: 'center' },
          { key: 'notes', header: 'Preparation Modifiers / Notes' }
        ],
        rows: (order.items || []).map((i: any) => ({
          name: i.name,
          quantity: `x${i.quantity}`,
          notes: i.modifiers && i.modifiers.length > 0 ? i.modifiers.join(', ') : 'Standard Preparation'
        })),
        metadata: {
          'Destination': order.roomNumber ? `ROOM ${order.roomNumber}` : (order.tableNumber ? `TABLE ${order.tableNumber}` : 'Direct Counter'),
          'Order Type': order.orderType || 'Dine-In',
          'Server / Steward': order.stewardName || order.serverName || 'F&B Staff',
          'Guest': order.guestName || 'Walk-In Guest',
          'Chef Notes': order.inRoomDiningDetails?.kitchenNotes || order.notes || 'None',
          'KOT Status': order.kotStatus || 'In Kitchen'
        },
        footerNotes: [
          '80mm Thermal KOT Print Voucher',
          'LESync Kitchen Display & KOT Routing'
        ]
      }, filename);
    }

    return this.exportToPDF({
      title: `POS GUEST BILL - ${order.orderNumber}`,
      subtitle: `${resortName.toUpperCase()} • ${outlet.toUpperCase()}`,
      referenceNumber: order.orderNumber,
      date: order.createdAt || new Date().toISOString(),
      propertyName: resortName,
      logoUrl: sysSettings?.logoUrl,
      columns: [
        { key: 'name', header: 'Item Description' },
        { key: 'quantity', header: 'Qty', align: 'center' },
        { key: 'unitPrice', header: 'Rate (BDT)', align: 'right' },
        { key: 'total', header: 'Total (BDT)', align: 'right' }
      ],
      rows: (order.items || []).map((i: any) => ({
        name: i.name + (i.modifiers && i.modifiers.length > 0 ? ` (${i.modifiers.join(', ')})` : ''),
        quantity: i.quantity,
        unitPrice: `BDT ${(i.unitPrice || 0).toLocaleString()}`,
        total: `BDT ${(i.totalPrice || i.total || (i.unitPrice * i.quantity) || 0).toLocaleString()}`
      })),
      summaryTotals: {
        name: 'Total Amount Payable',
        total: order.total
      },
      metadata: {
        'Location': order.roomNumber ? `Room ${order.roomNumber}` : (order.tableNumber ? `Table ${order.tableNumber}` : 'Takeaway / Counter'),
        'Guest': order.guestName || 'Restaurant Guest',
        'Subtotal': `BDT ${(order.subtotal || 0).toLocaleString()}`,
        'VAT (15%)': `BDT ${(order.tax || Math.round((order.subtotal || 0) * 0.15)).toLocaleString()}`,
        'Service Charge (10%)': `BDT ${(order.serviceCharge || Math.round((order.subtotal || 0) * 0.10)).toLocaleString()}`,
        'Grand Total': `BDT ${(order.total || 0).toLocaleString()}`,
        'Payment Tender': order.paymentMethod || 'Direct Payment',
        'Payment Status': order.paymentStatus === 'Billed-To-Room' ? 'Charged to Room Folio' : (order.voided ? 'VOIDED' : 'Paid & Settled')
      },
      footerNotes: [
        '80mm Thermal Receipt Voucher',
        'Thank you for dining with us! Please visit again.'
      ]
    }, filename);
  },

  /**
   * Export Guest Master Folio Statement to PDF
   */
  exportFolioToPDF(folio: Folio, propertyName?: string): boolean {
    const sysSettings = pmsService.getState()?.settings;
    const resortName = propertyName || sysSettings?.resortName || 'Hotel & Resort PMS';
    const filename = `Folio_${folio.folioNumber || 'FOLIO'}.pdf`;

    const chargesRows = ((folio.items as any[]) || []).map(c => ({
      date: c.date ? new Date(c.date).toLocaleDateString('en-GB') : '-',
      description: c.description || c.category || 'Charge Item',
      department: c.department || c.category || 'Front Desk',
      reference: c.id?.slice(0, 8) || '-',
      amount: c.totalAmount ?? c.amount ?? 0
    }));

    return this.exportToPDF({
      title: `GUEST MASTER FOLIO - ${folio.folioNumber}`,
      subtitle: `${resortName.toUpperCase()} • OFFICIAL FOLIO STATEMENT`,
      referenceNumber: folio.folioNumber,
      date: new Date().toLocaleDateString('en-GB'),
      propertyName: resortName,
      logoUrl: sysSettings?.logoUrl,
      columns: [
        { key: 'date', header: 'Date' },
        { key: 'description', header: 'Description / Item' },
        { key: 'department', header: 'Dept' },
        { key: 'reference', header: 'Ref #' },
        { key: 'amount', header: 'Amount (BDT)', align: 'right' }
      ],
      rows: chargesRows,
      summaryTotals: {
        description: 'Current Net Balance Due',
        amount: folio.balance
      },
      metadata: {
        'Guest Name': folio.guestName,
        'Room Number': folio.roomNumber,
        'Folio Status': folio.status?.toUpperCase(),
        'Subtotal': `BDT ${(folio.subtotal || 0).toLocaleString()}`,
        'VAT / Tax': `BDT ${(folio.taxTotal || 0).toLocaleString()}`,
        'Service Charge': `BDT ${(folio.serviceChargeTotal || 0).toLocaleString()}`,
        'Grand Total': `BDT ${(folio.grandTotal || 0).toLocaleString()}`,
        'Paid Total': `BDT ${(folio.paidTotal || 0).toLocaleString()}`,
        'Balance': `BDT ${(folio.balance || 0).toLocaleString()}`
      }
    }, filename);
  },

  /**
   * Export Payment Receipt to PDF
   */
  exportPaymentReceiptToPDF(payment: Payment, propertyName?: string): boolean {
    const sysSettings = pmsService.getState()?.settings;
    const resortName = propertyName || sysSettings?.resortName || 'Hotel & Resort PMS';
    const filename = `Receipt_${payment.transactionNumber || 'REC'}.pdf`;
    const pAny = payment as any;

    return this.exportToPDF({
      title: `MONEY RECEIPT - ${payment.transactionNumber}`,
      subtitle: `${resortName.toUpperCase()} • OFFICIAL PAYMENT ACKNOWLEDGEMENT`,
      referenceNumber: payment.transactionNumber,
      date: payment.createdAt ? new Date(payment.createdAt).toLocaleString() : new Date().toLocaleString(),
      propertyName: resortName,
      logoUrl: sysSettings?.logoUrl,
      columns: [
        { key: 'field', header: 'Particulars' },
        { key: 'value', header: 'Transaction Record' }
      ],
      rows: [
        { field: 'Receipt / Transaction #', value: payment.transactionNumber },
        { field: 'Received From (Guest)', value: pAny.guestName || 'Guest' },
        { field: 'Room / Folio #', value: `${pAny.roomNumber || '-'} / ${pAny.folioNumber || payment.folioId || '-'}` },
        { field: 'Payment Method', value: (pAny.paymentMethod || payment.method)?.toUpperCase() },
        { field: 'Payment Purpose', value: pAny.paymentType || 'Guest Settlement' },
        { field: 'Settlement Amount', value: `BDT ${(payment.amount || 0).toLocaleString()}` },
        { field: 'Transaction Status', value: payment.status?.toUpperCase() || 'CONFIRMED' },
        { field: 'Cashier / Duty Officer', value: pAny.recordedBy || payment.createdBy || 'Front Desk Officer' },
        { field: 'Reference / Voucher', value: payment.reference || pAny.voucherNumber || '-' }
      ],
      metadata: {
        'Amount Paid': `BDT ${(payment.amount || 0).toLocaleString()}`,
        'Payment Mode': (pAny.paymentMethod || payment.method)?.toUpperCase(),
        'Status': payment.status?.toUpperCase() || 'CONFIRMED'
      }
    }, filename);
  },

  /**
   * Export Reservation Confirmation Voucher to PDF
   * Accurately matches the Agoda-style booking voucher layout shown on the application screen.
   * Generates a 100% crisp, self-contained vector PDF with exact fonts, colored dot badges,
   * repeating ribbon banner, form boxes, stay schedule, dual signature blocks, remarks and notes.
   */
  async exportReservationToPDF(reservation: Reservation, propertyName?: string): Promise<boolean> {
    const sysSettings = pmsService.getState()?.settings;
    const resortName = propertyName || sysSettings?.resortName || 'LESync Resort & Convention Hall';
    const address = sysSettings?.address || 'Purbachal Link Road, Gazipur / Dhaka, Bangladesh';
    const phone = sysSettings?.phone || '+880 1711-223344 / +880 9612-445566';
    const email = sysSettings?.email || 'reservation@lesyncresort.com';
    const filename = `Reservation_Confirmation_${reservation.reservationNumber || 'RES'}.pdf`;

    // 1. If the exact on-screen Agoda voucher element is available in DOM, capture it directly with lossless 300 DPI PNG
    if (typeof document !== 'undefined') {
      const voucherEl = document.getElementById('voucher-card') || document.getElementById('printable-document');
      if (voucherEl) {
        try {
          const success = await this.exportElementToPDF(voucherEl, filename, {
            scale: 3,
            margin: 6,
            metadata: {
              title: `Reservation Confirmation Voucher - ${reservation.reservationNumber}`,
              subject: `Official Agoda booking confirmation voucher for ${reservation.guestName || 'Guest'}`,
              author: resortName,
              creator: `${resortName} PMS Agoda Voucher Engine`
            }
          });
          if (success) return true;
        } catch (e) {
          console.warn('DOM capture of voucher-card failed, falling back to vector generator:', e);
        }
      }
    }

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const rAny = reservation as any;
      const guests = pmsService.getState()?.guests;
      const guest = reservation.guestId ? guests?.find(g => g.id === reservation.guestId) : undefined;
      const guestCode = guest?.guestCode || (reservation.guestId ? reservation.guestId.slice(-8).toUpperCase() : 'GST-2026-00103');
      const currentUser = pmsService.getState()?.currentUser;
      const staffName = reservation.createdBy || currentUser?.name || 'Front Desk Staff';

      const formatVoucherDate = (dateStr?: string) => {
        if (!dateStr) return '-';
        try {
          const d = new Date(dateStr);
          if (isNaN(d.getTime())) return dateStr;
          return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
        } catch {
          return dateStr;
        }
      };

      const getFreeCancelDate = (arrivalDateStr?: string) => {
        if (!arrivalDateStr) return '2 days prior to check-in';
        try {
          const d = new Date(arrivalDateStr);
          d.setDate(d.getDate() - 2);
          return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
        } catch {
          return '2 days prior to check-in';
        }
      };

      const arrivalFormatted = formatVoucherDate(reservation.arrivalDate);
      const departureFormatted = formatVoucherDate(reservation.departureDate);
      const freeCancelFormatted = getFreeCancelDate(reservation.arrivalDate);
      const residenceStr = guest?.country || guest?.nationality ? `${guest.country || guest.nationality}${guest.city ? ` / ${guest.city}` : ''}` : 'Bangladesh / Dhaka';
      const refNumber = reservation.id ? reservation.id.slice(-8).toUpperCase() : '70543502';
      const firstWord = resortName.split(' ')[0] || 'LESync';
      const firstChar = firstWord.charAt(0).toUpperCase();

      // Function to draw the outer page border on current page
      const drawPageOuterBorder = () => {
        doc.setDrawColor(15, 23, 42); // slate-900
        doc.setLineWidth(0.6);
        doc.roundedRect(8, 8, 194, 281, 2.5, 2.5, 'S');
      };

      // Draw initial page border
      drawPageOuterBorder();

      // =========================================================================
      // 1. TOP HEADER: Brand Logo, Colored Dots & Booking Confirmation Title
      // =========================================================================
      // Left: Logo Monogram box or Logo image
      let logoRendered = false;
      if (sysSettings?.logoUrl && typeof sysSettings.logoUrl === 'string' && sysSettings.logoUrl.startsWith('data:image')) {
        try {
          const isPng = sysSettings.logoUrl.startsWith('data:image/png');
          doc.addImage(sysSettings.logoUrl, isPng ? 'PNG' : 'JPEG', 12, 11, 28, 10);
          logoRendered = true;
        } catch {
          logoRendered = false;
        }
      }

      if (!logoRendered) {
        doc.setFillColor(15, 23, 42); // #0f172a
        doc.roundedRect(12, 11, 8.5, 8.5, 1.2, 1.2, 'F');
        doc.setTextColor(245, 158, 11); // amber-400
        doc.setFont('times', 'bold');
        doc.setFontSize(12);
        doc.text(firstChar, 16.25, 17.2, { align: 'center' });

        // Brand Word beside monogram (e.g. "lesync")
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text(firstWord.toLowerCase(), 22.5, 17.5);
      }

      // 5-dot colored circles (Red, Yellow/Amber, Green, Blue, Purple)
      const dotY = 22.2;
      doc.setFillColor(225, 29, 72); // Red #e11d48
      doc.circle(13.5, dotY, 1.2, 'F');
      doc.setFillColor(245, 158, 11); // Amber #f59e0b
      doc.circle(17.5, dotY, 1.2, 'F');
      doc.setFillColor(16, 185, 129); // Green #10b981
      doc.circle(21.5, dotY, 1.2, 'F');
      doc.setFillColor(59, 130, 246); // Blue #3b82f6
      doc.circle(25.5, dotY, 1.2, 'F');
      doc.setFillColor(139, 92, 246); // Purple #8b5cf6
      doc.circle(29.5, dotY, 1.2, 'F');

      // Right: Booking Confirmation Title
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(20);
      const confText = 'Confirmation';
      const confWidth = doc.getTextWidth(confText);
      doc.setTextColor(15, 23, 42);
      doc.text('Booking ', 198 - confWidth, 17.5, { align: 'right' });
      doc.setTextColor(225, 29, 72); // Red #e11d48
      doc.text(confText, 198, 17.5, { align: 'right' });

      // Sub-caption under title
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.8);
      doc.setTextColor(71, 85, 105);
      doc.text('Please present either an electronic or paper copy of your hotel voucher upon check-in.', 198, 21.5, { align: 'right' });

      // =========================================================================
      // 2. REPEATING SLATE RIBBON BAR
      // =========================================================================
      const ribbonY = 25.2;
      const ribbonH = 4.8;
      doc.setFillColor(203, 213, 225); // #cbd5e1
      doc.rect(8, ribbonY, 194, ribbonH, 'F');
      doc.setDrawColor(148, 163, 184);
      doc.setLineWidth(0.2);
      doc.line(8, ribbonY, 202, ribbonY);
      doc.line(8, ribbonY + ribbonH, 202, ribbonY + ribbonH);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6);
      doc.setTextColor(71, 85, 105);
      const repeatedBrand = Array(7).fill(cleanPdfText(resortName.toUpperCase())).join('   ');
      doc.text(repeatedBrand, 105, ribbonY + 3.3, { align: 'center' });

      let currentY = ribbonY + ribbonH + 2.5;

      // =========================================================================
      // 3. OPTIONAL CORPORATE OR GROUP BANNER
      // =========================================================================
      const isCorporate = reservation.customerType === 'Corporate' && Boolean(reservation.companyName);
      const isGroup = Boolean(reservation.isGroupBooking && reservation.groupName);

      if (isCorporate || isGroup) {
        const bannerH = 6.2;
        doc.setFillColor(isCorporate ? 239 : 250, isCorporate ? 246 : 245, isCorporate ? 255 : 255);
        doc.setDrawColor(isCorporate ? 147 : 216, isCorporate ? 197 : 180, isCorporate ? 253 : 254);
        doc.roundedRect(12, currentY, 186, bannerH, 1, 1, 'FD');

        if (isCorporate) {
          doc.setFillColor(219, 234, 254);
          doc.roundedRect(14, currentY + 1.2, 26, 3.8, 0.8, 0.8, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(6);
          doc.setTextColor(30, 58, 138);
          doc.text('CORPORATE ACCOUNT', 27, currentY + 3.8, { align: 'center' });

          doc.setFontSize(7.5);
          doc.setTextColor(15, 23, 42);
          doc.text(cleanPdfText(reservation.companyName || ''), 42, currentY + 4.2);

          if (reservation.companyGstBin) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(6.5);
            doc.setTextColor(100, 116, 139);
            doc.text(`(BIN: ${cleanPdfText(reservation.companyGstBin)})`, 44 + doc.getTextWidth(reservation.companyName || ''), currentY + 4.2);
          }
        } else if (isGroup) {
          doc.setFillColor(243, 232, 255);
          doc.roundedRect(14, currentY + 1.2, 22, 3.8, 0.8, 0.8, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(6);
          doc.setTextColor(88, 28, 135);
          doc.text('GROUP BOOKING', 25, currentY + 3.8, { align: 'center' });

          doc.setFontSize(7.5);
          doc.setTextColor(15, 23, 42);
          doc.text(cleanPdfText(reservation.groupName || ''), 38, currentY + 4.2);

          if (reservation.groupLeaderName) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(6.5);
            doc.setTextColor(71, 85, 105);
            doc.text(`• Leader: ${cleanPdfText(reservation.groupLeaderName)}`, 40 + doc.getTextWidth(reservation.groupName || ''), currentY + 4.2);
          }
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6.8);
        doc.setTextColor(71, 85, 105);
        doc.text(`Total Rooms: ${reservation.totalRoomsCount || reservation.allocatedRooms?.length || 1}`, 195, currentY + 4.2, { align: 'right' });

        currentY += bannerH + 2.5;
      }

      // =========================================================================
      // 4. TWO-COLUMN DETAILS GRID (Left info + Right 6 Agoda Form Boxes)
      // =========================================================================
      const gridStartY = currentY;

      // --- LEFT COLUMN (X = 12 to 101, W = 89) ---
      const leftRows: Array<{ label: string; val: string; bold: boolean }> = [
        { label: 'Booking ID :', val: reservation.reservationNumber || 'RES-2026-00462', bold: true },
        { label: 'Booking Reference No :', val: refNumber, bold: false },
        { label: reservation.customerType === 'Corporate' ? 'Lead Delegate :' : 'Client :', val: (reservation.guestName || 'AZ LABIB').toUpperCase(), bold: true }
      ];

      if (reservation.customerType === 'Corporate' && reservation.companyName) {
        leftRows.push({ label: 'Corporate Client :', val: reservation.companyName, bold: true });
        if (reservation.companyContactPerson) {
          leftRows.push({ label: 'Booked By / Contact :', val: `${reservation.companyContactPerson}${reservation.companyDesignation ? ` (${reservation.companyDesignation})` : ''}`, bold: false });
        }
      }

      leftRows.push(
        { label: 'Member ID :', val: guestCode, bold: false },
        { label: 'Country of Residence :', val: residenceStr, bold: false }
      );

      let curLeftY = gridStartY + 2.5;
      const rowStep = leftRows.length > 5 ? 3.8 : 4.3;
      leftRows.forEach(row => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6.8);
        doc.setTextColor(71, 85, 105);
        doc.text(row.label, 12, curLeftY);

        doc.setFont('helvetica', row.bold ? 'bold' : 'normal');
        doc.setFontSize(row.bold ? 7.8 : 7.0);
        doc.setTextColor(15, 23, 42);
        doc.text(cleanPdfText(row.val), 48, curLeftY);
        curLeftY += rowStep;
      });

      // 3 Stacked Left Rounded Form Boxes: Property, Address, Contact
      curLeftY += 1.0;
      const leftBoxH = 6.8;

      // Box 1: Property / Hotel
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.2);
      doc.setTextColor(100, 116, 139);
      doc.text('Property :', 12, curLeftY + 2.2);
      doc.setFontSize(5.5);
      doc.text('Hotel :', 12, curLeftY + 4.8);

      doc.setDrawColor(203, 213, 225);
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(12, curLeftY + 5.5, 89, leftBoxH, 1, 1, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(15, 23, 42);
      doc.text(cleanPdfText(resortName), 14, curLeftY + 10.0);

      curLeftY += leftBoxH + 7.0;

      // Box 2: Address
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.2);
      doc.setTextColor(100, 116, 139);
      doc.text('Address :', 12, curLeftY + 2.2);

      doc.roundedRect(12, curLeftY + 3.2, 89, leftBoxH, 1, 1, 'FD');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.8);
      doc.setTextColor(30, 41, 59);
      doc.text(cleanPdfText(address), 14, curLeftY + 7.5);

      curLeftY += leftBoxH + 4.5;

      // Box 3: Property Contact Number
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.2);
      doc.setTextColor(100, 116, 139);
      doc.text('Property Contact Number :', 12, curLeftY + 2.2);
      doc.setFontSize(5.5);
      doc.text('Hotel Contact Number :', 12, curLeftY + 4.8);

      doc.roundedRect(12, curLeftY + 5.5, 89, leftBoxH, 1, 1, 'FD');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.8);
      doc.setTextColor(15, 23, 42);
      doc.text(cleanPdfText(`${phone} • ${email}`), 14, curLeftY + 10.0);

      const leftColBottomY = curLeftY + leftBoxH + 5.5;

      // --- RIGHT COLUMN: 6 Stacked Agoda Form Boxes (X = 105 to 198, W = 93) ---
      const totalRoomsStr = String(reservation.totalRoomsCount || reservation.allocatedRooms?.length || 1);
      const roomTypeLabel = reservation.allocatedRooms && reservation.allocatedRooms.length > 1
        ? `${reservation.allocatedRooms.length} Rooms Allocated`
        : (reservation.roomTypeName || 'Deluxe Room');

      const promoText = reservation.packageName || (
        reservation.customerType === 'Corporate'
          ? 'Corporate Negotiated Rate & Breakfast'
          : 'Best Flexible Rate with Complimentary Breakfast'
      );

      const rightBoxes = [
        { label: 'Number of Rooms :', sub: 'Total Rooms :', val: totalRoomsStr, boldVal: true, size: 9.5 },
        { label: 'Number of Extra Beds :', sub: null, val: '0', boldVal: true, size: 8.5 },
        { label: 'Number of Adults :', sub: null, val: String(reservation.adults || 2), boldVal: true, size: 8.5 },
        { label: 'Number of Children :', sub: null, val: String(reservation.children || 0), boldVal: true, size: 8.5 },
        { label: 'Room Type :', sub: null, val: roomTypeLabel, boldVal: true, size: 8.0 },
        { label: 'Promotion :', sub: null, val: promoText, boldVal: false, size: 6.8 }
      ];

      let rBoxY = gridStartY;
      const boxH = 6.8;
      const boxGap = 1.3;
      rightBoxes.forEach(rb => {
        // Left label cell
        doc.setDrawColor(203, 213, 225);
        doc.setFillColor(241, 245, 249); // #f1f5f9
        doc.roundedRect(105, rBoxY, 41, boxH, 1, 1, 'FD');

        // Right value cell
        doc.setFillColor(255, 255, 255);
        doc.roundedRect(146, rBoxY, 52, boxH, 1, 1, 'FD');

        // Label text
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6.5);
        doc.setTextColor(51, 65, 85);
        if (rb.sub) {
          doc.text(rb.label, 107, rBoxY + 2.8);
          doc.setFontSize(5.2);
          doc.setTextColor(148, 163, 184);
          doc.text(rb.sub, 107, rBoxY + 5.5);
        } else {
          doc.text(rb.label, 107, rBoxY + 4.4);
        }

        // Value text
        doc.setFont('helvetica', rb.boldVal ? 'bold' : 'normal');
        doc.setFontSize(rb.size);
        doc.setTextColor(15, 23, 42);
        const maxValW = 50;
        const valStr = cleanPdfText(rb.val);
        const wrappedVal = doc.splitTextToSize(valStr, maxValW);
        if (wrappedVal.length > 1) {
          doc.setFontSize(6.2);
          doc.text(wrappedVal[0], 172, rBoxY + 2.8, { align: 'center' });
          doc.text(wrappedVal[1], 172, rBoxY + 5.5, { align: 'center' });
        } else {
          doc.text(valStr, 172, rBoxY + 4.5, { align: 'center' });
        }

        rBoxY += boxH + boxGap;
      });

      // Promotion note under the 6 boxes
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(6.0);
      doc.setTextColor(100, 116, 139);
      doc.text('For Full Promotion details and conditions see confirmation email', 198, rBoxY + 1.0, { align: 'right' });

      currentY = Math.max(leftColBottomY, rBoxY + 3.0);

      // =========================================================================
      // 5. ALLOCATED ROOMS & OCCUPANTS SCHEDULE TABLE (if rooms allocated)
      // =========================================================================
      const allocatedRooms = reservation.allocatedRooms || [];
      if (allocatedRooms.length > 0) {
        const tableY = currentY;
        const arrD = new Date(reservation.arrivalDate);
        const depD = new Date(reservation.departureDate);
        const nights = Math.max(1, Math.round((depD.getTime() - arrD.getTime()) / (1000 * 60 * 60 * 24)));

        // Table Header Bar (Dark Slate-900)
        doc.setFillColor(15, 23, 42);
        doc.roundedRect(12, tableY, 186, 5.0, 1, 1, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6.5);
        doc.setTextColor(255, 255, 255);
        doc.text(`Room Allocation & Occupancy Schedule (${allocatedRooms.length} ${allocatedRooms.length === 1 ? 'Room' : 'Rooms'})`, 15, tableY + 3.5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6.2);
        doc.setTextColor(245, 158, 11); // amber-400
        doc.text(`${arrivalFormatted} -> ${departureFormatted} (${nights} ${nights === 1 ? 'Night' : 'Nights'})`, 195, tableY + 3.5, { align: 'right' });

        // Column Titles Row
        const colY = tableY + 5.0;
        doc.setFillColor(241, 245, 249);
        doc.rect(12, colY, 186, 4.0, 'F');
        doc.setDrawColor(203, 213, 225);
        doc.setLineWidth(0.2);
        doc.rect(12, colY, 186, 4.0, 'S');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(5.8);
        doc.setTextColor(51, 65, 85);
        doc.text('Room #', 16, colY + 2.8);
        doc.text('Room Category', 36, colY + 2.8);
        doc.text('Allocated Occupant', 86, colY + 2.8);
        doc.text('Occupancy', 140, colY + 2.8, { align: 'center' });
        doc.text('Daily Rate', 166, colY + 2.8, { align: 'right' });
        doc.text('Est. Room Total', 195, colY + 2.8, { align: 'right' });

        let rowY = colY + 4.0;
        // Limit on page 1 to prevent pushing notes off page; 3 rooms fit on 1 page
        const roomsToDisplay = allocatedRooms.slice(0, 3);
        roomsToDisplay.forEach((ar, idx) => {
          doc.setFillColor(idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 252);
          doc.rect(12, rowY, 186, 4.2, 'F');
          doc.setDrawColor(226, 232, 240);
          doc.line(12, rowY + 4.2, 198, rowY + 4.2);

          doc.setFont('helvetica', 'bold');
          doc.setFontSize(6.2);
          doc.setTextColor(15, 23, 42);
          doc.text(ar.roomNumber ? `Rm ${ar.roomNumber}` : `#${idx + 1}`, 16, rowY + 3.0);

          doc.setFont('helvetica', 'normal');
          doc.text(cleanPdfText(ar.roomTypeName || reservation.roomTypeName), 36, rowY + 3.0);

          doc.setFont('helvetica', 'bold');
          doc.text(cleanPdfText(ar.guestName || reservation.guestName), 86, rowY + 3.0);
          if (ar.guestPhone) {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(5.5);
            doc.setTextColor(100, 116, 139);
            doc.text(`(${ar.guestPhone})`, 87 + doc.getTextWidth(ar.guestName || reservation.guestName), rowY + 3.0);
          }

          doc.setFont('helvetica', 'normal');
          doc.setFontSize(6.0);
          doc.setTextColor(51, 65, 85);
          doc.text(`${ar.adults || 2}A ${ar.children ? `+${ar.children}C` : ''}`, 140, rowY + 3.0, { align: 'center' });

          doc.text(`BDT ${(ar.rate || 0).toLocaleString()}`, 166, rowY + 3.0, { align: 'right' });
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(15, 23, 42);
          doc.text(`BDT ${((ar.rate || 0) * nights).toLocaleString()}`, 195, rowY + 3.0, { align: 'right' });

          rowY += 4.2;
        });

        // Summary footer row
        doc.setFillColor(241, 245, 249);
        doc.rect(12, rowY, 186, 3.8, 'F');
        doc.setDrawColor(203, 213, 225);
        doc.rect(12, rowY, 186, 3.8, 'S');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(5.8);
        doc.setTextColor(51, 65, 85);
        doc.text(`SCHEDULE TOTAL: ${allocatedRooms.length} ${allocatedRooms.length === 1 ? 'ROOM' : 'ROOMS'}`, 16, rowY + 2.7);
        doc.text(`BDT ${(reservation.totalEstimatedAmount || 0).toLocaleString()}`, 195, rowY + 2.7, { align: 'right' });

        currentY = rowY + 5.5;
      }

      // =========================================================================
      // 6. CANCELLATION POLICY BOX
      // =========================================================================
      const cancelBoxH = 10.5;
      doc.setFillColor(241, 245, 249); // slate-100
      doc.setDrawColor(203, 213, 225);
      doc.roundedRect(12, currentY, 186, cancelBoxH, 1, 1, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.8);
      doc.setTextColor(15, 23, 42);
      doc.text('Cancellation Policy: ', 14, currentY + 3.8);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.2);
      doc.setTextColor(30, 41, 59);
      const cancelMsg = `Stay flexible! Cancel for free before ${freeCancelFormatted}. Any cancellation received within 1 day prior to the arrival date will incur the first night's charge. Failure to arrive at your hotel or property will be treated as a No-Show and will incur a charge of 100% of the booking value (Hotel policy).`;
      const wrappedCancel = doc.splitTextToSize(cancelMsg, 155);
      doc.text(wrappedCancel, 41, currentY + 3.8);

      currentY += cancelBoxH + 2.0;

      // =========================================================================
      // 7. BENEFITS INCLUDED BAR
      // =========================================================================
      const benBarH = 5.2;
      doc.setFillColor(226, 232, 240); // slate-200
      doc.setDrawColor(203, 213, 225);
      doc.roundedRect(12, currentY, 186, benBarH, 1, 1, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.8);
      doc.setTextColor(15, 23, 42);
      doc.text('Benefits Included ', 14, currentY + 3.6);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 41, 59);
      doc.text('Free WiFi, Breakfast', 39, currentY + 3.6);

      currentY += benBarH + 2.5;

      // =========================================================================
      // 8. DATES, PAYMENT & SIGNATURES BLOCK
      // =========================================================================
      const blockH = 43.0;
      doc.setDrawColor(203, 213, 225);
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(12, currentY, 186, blockH, 1, 1, 'FD');

      // Top banner: Arrival and Departure (H: 6.8mm)
      doc.setFillColor(241, 245, 249);
      doc.rect(12, currentY, 186, 6.8, 'FD');
      doc.line(105, currentY, 105, currentY + 6.8);

      // Arrival
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.0);
      doc.setTextColor(71, 85, 105);
      doc.text('Arrival :', 15, currentY + 4.6);
      doc.setTextColor(15, 23, 42);
      doc.text(arrivalFormatted, 28, currentY + 4.6);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.2);
      doc.setTextColor(100, 116, 139);
      doc.text('(From 14:00)', 68, currentY + 4.6);

      // Departure
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.0);
      doc.setTextColor(71, 85, 105);
      doc.text('Departure :', 108, currentY + 4.6);
      doc.setTextColor(15, 23, 42);
      doc.text(departureFormatted, 126, currentY + 4.6);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.2);
      doc.setTextColor(100, 116, 139);
      doc.text('(Until 12:00)', 166, currentY + 4.6);

      // --- Lower Left: Payment Method & Booked and Payable Through ---
      const innerLeftY = currentY + 8.5;

      // Two rounded mini cards
      doc.setFillColor(241, 245, 249);
      doc.roundedRect(15, innerLeftY, 41, 9.2, 0.8, 0.8, 'FD');
      doc.roundedRect(58, innerLeftY, 43, 9.2, 0.8, 0.8, 'FD');

      // Payment method card
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(5.8);
      doc.setTextColor(100, 116, 139);
      doc.text('Payment Method :', 17, innerLeftY + 3.2);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.8);
      doc.setTextColor(30, 41, 59);
      doc.text(cleanPdfText(reservation.bookingSource || 'Phone / Direct'), 17, innerLeftY + 7.0);

      // Card No card
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(5.8);
      doc.setTextColor(100, 116, 139);
      doc.text('Card No :', 60, innerLeftY + 3.2);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.8);
      doc.setTextColor(30, 41, 59);
      doc.text('XXXX-XXXX-XXXX-4031', 60, innerLeftY + 7.0);

      // Booked and Payable Through
      const payThroughY = innerLeftY + 11.2;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.5);
      doc.setTextColor(51, 65, 85);
      doc.text('Booked And Payable Through :', 15, payThroughY + 1.8);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(5.5);
      doc.setTextColor(148, 163, 184);
      doc.text('Booked And Payable By :', 15, payThroughY + 4.5);

      doc.setFillColor(248, 250, 252);
      doc.roundedRect(15, payThroughY + 5.8, 86, 15.5, 0.8, 0.8, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.0);
      doc.setTextColor(15, 23, 42);
      doc.text(cleanPdfText(resortName), 17, payThroughY + 9.8);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.2);
      doc.setTextColor(51, 65, 85);
      doc.text(cleanPdfText(address), 17, payThroughY + 14.0);
      doc.text(`Hotline: ${cleanPdfText(phone)}`, 17, payThroughY + 18.2);

      // --- Lower Right: Signature Box (X = 106 to 195, W = 89, H = 33) ---
      const sigBoxX = 106;
      const sigBoxY = currentY + 8.5;
      const sigBoxW = 89;
      const sigBoxH = 32.5;
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(sigBoxX, sigBoxY, sigBoxW, sigBoxH, 0.8, 0.8, 'FD');

      // 1. Guest Signature
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.8);
      doc.setTextColor(30, 41, 59);
      doc.text('GUEST SIGNATURE :', sigBoxX + 3, sigBoxY + 4.8);
      doc.setFont('helvetica', 'normal');
      doc.text(cleanPdfText(reservation.guestName || 'Valued Guest'), sigBoxX + sigBoxW - 3, sigBoxY + 4.8, { align: 'right' });

      // Signature line
      doc.setDrawColor(148, 163, 184);
      doc.line(sigBoxX + 3, sigBoxY + 12.0, sigBoxX + sigBoxW - 3, sigBoxY + 12.0);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(5.8);
      doc.setTextColor(148, 163, 184);
      doc.text('Signature of Guest at Check-in', sigBoxX + 3, sigBoxY + 14.8);

      // 2. Reserved By (Staff)
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.8);
      doc.setTextColor(30, 41, 59);
      doc.text('RESERVED BY :', sigBoxX + 3, sigBoxY + 21.5);

      // Staff Amber Pill Badge
      const staffW = doc.getTextWidth(staffName) + 6;
      doc.setFillColor(254, 243, 199); // amber-100 #fef3c7
      doc.setDrawColor(252, 211, 77); // amber-300 #fcd34d
      doc.roundedRect(sigBoxX + sigBoxW - staffW - 3, sigBoxY + 18.0, staffW, 4.8, 0.8, 0.8, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.5);
      doc.setTextColor(15, 23, 42);
      doc.text(staffName, sigBoxX + sigBoxW - (staffW / 2) - 3, sigBoxY + 21.3, { align: 'center' });

      // Staff signature line
      doc.setDrawColor(148, 163, 184);
      doc.line(sigBoxX + 3, sigBoxY + 28.5, sigBoxX + sigBoxW - 3, sigBoxY + 28.5);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(5.8);
      doc.setTextColor(148, 163, 184);
      doc.text('Authorized Staff Signature', sigBoxX + 3, sigBoxY + 31.2);

      // Date of reservation
      const resDate = new Date(reservation.createdAt || Date.now()).toLocaleDateString('en-GB');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(5.8);
      doc.setTextColor(100, 116, 139);
      doc.text(resDate, sigBoxX + sigBoxW - 3, sigBoxY + 31.2, { align: 'right' });

      currentY += blockH + 2.5;

      // =========================================================================
      // 9. REMARKS & FINANCIAL SCHEDULE
      // =========================================================================
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.2);
      doc.setTextColor(15, 23, 42);
      doc.text('Remarks :', 12, currentY + 3.0);

      const totalEst = reservation.totalEstimatedAmount || rAny.totalAmount || 13500;
      const deposit = reservation.paidAmount || reservation.depositAmount || 0;
      const balance = Math.max(0, totalEst - deposit);

      // Financial Schedule line
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.6);
      doc.setTextColor(30, 41, 59);
      let remLineY = currentY + 6.8;

      doc.text('Financial Schedule: ', 12, remLineY);
      let fX = 12 + doc.getTextWidth('Financial Schedule: ');
      doc.text('Total Estimated Charges: ', fX, remLineY);
      fX += doc.getTextWidth('Total Estimated Charges: ');
      doc.setFont('helvetica', 'bold');
      doc.text(`BDT ${totalEst.toLocaleString()} `, fX, remLineY);
      fX += doc.getTextWidth(`BDT ${totalEst.toLocaleString()} `);

      doc.setFont('helvetica', 'normal');
      doc.text('• Advance Deposit Received: ', fX, remLineY);
      fX += doc.getTextWidth('• Advance Deposit Received: ');
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(4, 120, 87); // emerald-700
      doc.text(`BDT ${deposit.toLocaleString()} `, fX, remLineY);
      fX += doc.getTextWidth(`BDT ${deposit.toLocaleString()} `);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 41, 59);
      doc.text('• Balance Payable at Check-in: ', fX, remLineY);
      fX += doc.getTextWidth('• Balance Payable at Check-in: ');
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(190, 18, 60); // rose-700
      doc.text(`BDT ${balance.toLocaleString()}`, fX, remLineY);

      remLineY += 3.6;

      // Primary Guest & Occupancy
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.5);
      doc.setTextColor(51, 65, 85);
      doc.text(`Primary Guest: ${cleanPdfText(reservation.guestName || 'Valued Guest')} (${reservation.adults || 2} Adults${(reservation.children || 0) > 0 ? `, ${reservation.children} Children` : ''})`, 12, remLineY);

      remLineY += 3.2;

      // Sub-note
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(6.0);
      doc.setTextColor(100, 116, 139);
      doc.text('All special requests are subject to availability upon arrival', 12, remLineY);

      if (reservation.specialRequests) {
        remLineY += 3.2;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6.0);
        doc.setTextColor(146, 64, 14); // amber-800
        doc.text(`Special Requests: ${cleanPdfText(reservation.specialRequests)}`, 12, remLineY);
      }

      currentY = remLineY + 2.5;

      // =========================================================================
      // 10. NOTES BOX (Agoda Iconic 4-bullet Notes Container)
      // =========================================================================
      const remainingHeight = 286 - currentY;
      const notesBoxH = Math.min(58, Math.max(48, remainingHeight));

      doc.setDrawColor(203, 213, 225);
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(12, currentY, 186, notesBoxH, 1, 1, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.2);
      doc.setTextColor(15, 23, 42);
      doc.text('Notes', 15, currentY + 4.2);

      // Bullet 1: IMPORTANT note with Red bullet
      let bY = currentY + 8.2;
      doc.setFillColor(225, 29, 72); // red dot
      doc.circle(15.5, bY - 0.8, 0.8, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.2);
      doc.setTextColor(220, 38, 38); // red-600
      doc.text('IMPORTANT: ', 18, bY);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.0);
      doc.setTextColor(71, 85, 105);
      const note1Rest = 'At check-in, you must present the credit card used to make this booking and a valid photo ID (NID/Passport) with the same name. Failure to do so may result in the hotel requesting additional payment or your reservation not being honored. If you have submitted additional documentation for a third party booking or paid via a different payment method, please disregard the note above.';
      const note1Wrapped = doc.splitTextToSize(note1Rest, 148);
      doc.text(note1Wrapped, 36, bY);
      bY += (note1Wrapped.length * 3.0) + 2.2;

      // Bullet 2: All rooms guaranteed
      doc.setFillColor(148, 163, 184); // slate-400 dot
      doc.circle(15.5, bY - 0.8, 0.7, 'F');
      const note2 = 'All rooms are guaranteed on the day of arrival. In the case of a no-show, your room(s) will be released and you will be subject to the terms and conditions of the Cancellation/No-Show Policy specified at the time you made the booking as well as noted in the Confirmation Email.';
      const note2Wrapped = doc.splitTextToSize(note2, 174);
      doc.text(note2Wrapped, 18, bY);
      bY += (note2Wrapped.length * 3.0) + 2.2;

      // Bullet 3: Mini-bar items
      doc.circle(15.5, bY - 0.8, 0.7, 'F');
      const note3 = 'The total price for this booking does not include mini-bar items, telephone usage, laundry service, etc. The hotel will bill you directly.';
      const note3Wrapped = doc.splitTextToSize(note3, 174);
      doc.text(note3Wrapped, 18, bY);
      bY += (note3Wrapped.length * 3.0) + 2.2;

      // Bullet 4: Breakfast children policy
      doc.circle(15.5, bY - 0.8, 0.7, 'F');
      const note4 = 'In cases where Breakfast is included with the room rate, please note that certain hotels may charge extra for children travelling with their parents. If applicable, the hotel will bill you directly. Upon arrival, if you have any questions, please verify with the hotel.';
      const note4Wrapped = doc.splitTextToSize(note4, 174);
      doc.text(note4Wrapped, 18, bY);

      // =========================================================================
      // TRIGGER DOWNLOAD
      // =========================================================================
      const cleanFileName = cleanPdfText(filename).replace(/\s+/g, '_');
      const roomLabel = (reservation as any).assignedRoomNumber || (reservation as any).roomNumber || reservation.roomTypeName || 'Room';
      return triggerPdfDownload(doc, cleanFileName, {
        title: `Reservation Confirmation Voucher - ${reservation.reservationNumber}`,
        subject: `Official booking voucher for ${reservation.guestName || 'Guest'} (${roomLabel})`,
        author: resortName,
        creator: `${resortName} Online Booking & Front Desk Engine`,
        keywords: `Reservation, Voucher, Confirmation, ${reservation.reservationNumber}, Hotel, PMS, Agoda`
      });
    } catch (err) {
      console.error('Failed to generate reservation voucher PDF:', err);
      return false;
    }
  },

  /**
   * Universal Fallback for any other document type (Checkouts, Reg-cards, Banquet Contracts, etc.)
   */
  exportGenericDocToPDF(docType: string, rawData: any, propertyName?: string): boolean {
    const sysSettings = pmsService.getState()?.settings;
    const resortName = propertyName || sysSettings?.resortName || 'Hotel & Resort PMS';
    const title = (rawData?.title || docType.replace(/-/g, ' ')).toUpperCase();
    const filename = `${docType}_${new Date().toISOString().split('T')[0]}.pdf`;

    // Flatten rawData key-values into clean 2-column rows
    const rows: { key: string; value: string }[] = [];
    if (typeof rawData === 'object' && rawData !== null) {
      Object.entries(rawData).forEach(([k, v]) => {
        if (typeof v !== 'object' && v !== undefined && v !== null) {
          rows.push({
            key: k.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
            value: typeof v === 'number' && (k.toLowerCase().includes('amount') || k.toLowerCase().includes('total') || k.toLowerCase().includes('price'))
              ? `BDT ${v.toLocaleString()}`
              : String(v)
          });
        }
      });
    }

    return this.exportToPDF({
      title,
      subtitle: `${resortName.toUpperCase()} • OFFICIAL RECORD`,
      date: new Date().toLocaleDateString('en-GB'),
      propertyName: resortName,
      logoUrl: sysSettings?.logoUrl,
      columns: [
        { key: 'key', header: 'Document Field' },
        { key: 'value', header: 'Recorded Detail' }
      ],
      rows: rows.length > 0 ? rows : [{ key: 'Status', value: 'Audited & Recorded in System' }]
    }, filename);
  },

  /**
   * Export Banquet & Convention Guest Quotation Pro-Forma to PDF
   * Specially crafted fixed-size, pixel-aligned layout with property/customer logo,
   * customized serial number, structured metadata grid, wrapped description table, and financial audit summary.
   */
  exportQuotationToPDF(quotation: BanquetQuotation, propertyName?: string): boolean {
    const sysSettings = pmsService.getState()?.settings;
    const resortName = propertyName || sysSettings?.resortName || 'Hotel & Resort PMS';
    const serialNo = quotation.customSerialNo || quotation.quotationNumber || 'QTN';
    const filename = `Quotation_${serialNo}.pdf`;
    const logoImg = quotation.propertyLogoUrl || sysSettings?.logoUrl;

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const pageWidth = doc.internal.pageSize.getWidth(); // 210mm
      const pageHeight = doc.internal.pageSize.getHeight(); // 297mm
      const margin = 14;
      const contentWidth = pageWidth - margin * 2; // 182mm
      let y = margin;

      // Header renderer for pages
      const drawQuotationHeader = (isFirstPage: boolean) => {
        // Top dark header bar
        doc.setFillColor(15, 23, 42); // slate-900
        doc.roundedRect(margin, y, contentWidth, 22, 1.5, 1.5, 'F');

        // Render Property Logo on all pages (Custom uploaded logo or prestigious vector crest)
        renderPdfPropertyLogo(doc, margin + 4, y + 3, 24, 16, logoImg, resortName);
        const textStartX = margin + 33;

        // Title text
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.text(cleanPdfText('BANQUET & CONVENTION PRO-FORMA QUOTATION'), textStartX, y + 8);

        // Subtitle text (Property Name)
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(245, 158, 11); // amber-500
        doc.text(cleanPdfText(`${resortName.toUpperCase()} | EVENT & CONVENTION SALES`), textStartX, y + 13);

        if (sysSettings?.website || sysSettings?.phone) {
          doc.setFontSize(6.5);
          doc.setTextColor(148, 163, 184); // slate-400
          const contactLine = [sysSettings.phone, sysSettings.email, sysSettings.website].filter(Boolean).join(' | ');
          doc.text(cleanPdfText(contactLine), textStartX, y + 18);
        }

        // Right side: Serial No & Date badge
        const rightBoxWidth = 52;
        const rightBoxX = margin + contentWidth - rightBoxWidth - 3;
        doc.setFillColor(30, 41, 59); // slate-800
        doc.roundedRect(rightBoxX, y + 3, rightBoxWidth, 16, 1, 1, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7);
        doc.setTextColor(203, 213, 225);
        doc.text('QUOTATION REF / SERIAL:', rightBoxX + 3, y + 7.5);

        doc.setFontSize(8.5);
        doc.setTextColor(253, 224, 71); // yellow-300
        doc.text(cleanPdfText(serialNo), rightBoxX + 3, y + 12);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6.5);
        doc.setTextColor(148, 163, 184);
        doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, rightBoxX + 3, y + 16.5);

        y += 25;

        // First Page: Client & Event Specifications Card
        if (isFirstPage) {
          doc.setFillColor(248, 250, 252); // slate-50
          doc.setDrawColor(203, 213, 225); // slate-300
          doc.roundedRect(margin, y, contentWidth, 34, 1.5, 1.5, 'FD');

          const col1W = contentWidth * 0.48;
          const col2X = margin + col1W + 4;
          const col2W = contentWidth - col1W - 4;

          // Left Subheading: Client Details
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(15, 23, 42); // slate-900
          doc.text('CLIENT & ORGANIZATION PARTICULARS', margin + 4, y + 6);

          doc.setDrawColor(226, 232, 240);
          doc.line(margin + 4, y + 7.5, margin + col1W - 4, y + 7.5);

          const clientRows = [
            ['Client Name', quotation.clientName],
            ['Company / Org', quotation.clientCompany || 'Private Event'],
            ['Contact Phone', quotation.clientPhone],
            ['Email / Address', [quotation.clientEmail, quotation.clientAddress].filter(Boolean).join(', ') || '-']
          ];

          let clientY = y + 12;
          clientRows.forEach(([lbl, val]) => {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7);
            doc.setTextColor(100, 116, 139);
            doc.text(`${cleanPdfText(lbl)}:`, margin + 4, clientY);

            doc.setFont('helvetica', 'bold');
            doc.setTextColor(30, 41, 59);
            const valStr = cleanPdfText(val);
            const trunc = valStr.length > 36 ? valStr.substring(0, 34) + '...' : valStr;
            doc.text(trunc, margin + 28, clientY);
            clientY += 5;
          });

          // Right Subheading: Event Specifications
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(15, 23, 42);
          doc.text('EVENT SPECIFICATIONS & SCHEDULE', col2X, y + 6);

          doc.line(col2X, y + 7.5, margin + contentWidth - 4, y + 7.5);

          const eventRows = [
            ['Event Occasion', quotation.eventName],
            ['Date & Schedule', `${quotation.eventDate} (${quotation.startTime} - ${quotation.endTime})`],
            ['Expected Pax', `${quotation.guestCount} Guests`],
            ['Valid Until', quotation.validUntil]
          ];

          let eventY = y + 12;
          eventRows.forEach(([lbl, val]) => {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7);
            doc.setTextColor(100, 116, 139);
            doc.text(`${cleanPdfText(lbl)}:`, col2X, eventY);

            doc.setFont('helvetica', 'bold');
            doc.setTextColor(30, 41, 59);
            const valStr = cleanPdfText(val);
            const trunc = valStr.length > 34 ? valStr.substring(0, 32) + '...' : valStr;
            doc.text(trunc, col2X + 26, eventY);
            eventY += 5;
          });

          y += 38;
        }
      };

      drawQuotationHeader(true);

      // Construct item rows
      interface QtnRow {
        category: string;
        description: string;
        qty: string;
        rate: number;
        total: number;
      }

      const rows: QtnRow[] = [];

      // 1. Halls
      quotation.halls.forEach(h => {
        rows.push({
          category: 'Venue & Hall',
          description: `${h.hallName} (${h.setupStyle || 'Banquet Style'})`,
          qty: '1 Day/Slot',
          rate: h.hallRate,
          total: h.hallRate
        });
      });

      // 2. Catering
      if (quotation.cateringTotal > 0) {
        const menuPreview = quotation.menuItems.map(m => m.name).join(', ');
        rows.push({
          category: 'Food & Catering',
          description: `Custom Menu Package (${quotation.menuItems.length} items: ${menuPreview})`,
          qty: `${quotation.guestCount} Pax`,
          rate: quotation.menuPricePerPerson,
          total: quotation.cateringTotal
        });
      }

      // 3. Rooms
      quotation.rooms.forEach(rm => {
        rows.push({
          category: 'Accommodation',
          description: `${rm.roomTypeName} (${rm.roomCount} Rooms x ${rm.nights} Night${rm.nights > 1 ? 's' : ''})`,
          qty: `${rm.roomCount * rm.nights} Nights`,
          rate: rm.ratePerNight,
          total: rm.totalAmount
        });
      });

      // 4. Additional Services
      quotation.additionalServices.forEach(s => {
        rows.push({
          category: s.category || 'AV / Decor',
          description: s.name,
          qty: String(s.quantity),
          rate: s.rate,
          total: s.total
        });
      });

      // Table Column Definitions with exact fixed millimeter widths and alignments
      // Total contentWidth = 182mm
      const colWidths = {
        sn: 10,       // SL #
        category: 32, // Category
        desc: 76,     // Service / Package Particulars
        qty: 20,      // Qty
        rate: 22,     // Unit Rate (BDT)
        total: 22     // Total (BDT)
      };

      const drawTableHeader = () => {
        doc.setFillColor(30, 41, 59); // slate-800
        doc.rect(margin, y, contentWidth, 7, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(7);
        doc.setTextColor(255, 255, 255);

        let curX = margin;
        // SL
        doc.text('#', curX + colWidths.sn / 2, y + 4.8, { align: 'center' });
        curX += colWidths.sn;
        // Category
        doc.text('CATEGORY', curX + 2, y + 4.8);
        curX += colWidths.category;
        // Particulars
        doc.text('SERVICE & FACILITY PARTICULARS', curX + 2, y + 4.8);
        curX += colWidths.desc;
        // Qty
        doc.text('QTY / PAX', curX + colWidths.qty / 2, y + 4.8, { align: 'center' });
        curX += colWidths.qty;
        // Rate
        doc.text('RATE (BDT)', curX + colWidths.rate - 2, y + 4.8, { align: 'right' });
        curX += colWidths.rate;
        // Total
        doc.text('TOTAL (BDT)', curX + colWidths.total - 2, y + 4.8, { align: 'right' });

        y += 7;
      };

      drawTableHeader();

      // Render Item Rows with Multi-line Wrapping
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);

      rows.forEach((row, idx) => {
        // Split description to fit inside colWidths.desc (76mm)
        const descLines = doc.splitTextToSize(cleanPdfText(row.description), colWidths.desc - 4);
        const rowHeight = Math.max(6, descLines.length * 3.8 + 2.5);

        // Check page boundary
        if (y + rowHeight > pageHeight - 65) {
          doc.addPage();
          y = margin;
          drawQuotationHeader(false);
          drawTableHeader();
        }

        // Alternating row background
        if (idx % 2 === 1) {
          doc.setFillColor(248, 250, 252); // slate-50
          doc.rect(margin, y, contentWidth, rowHeight, 'F');
        }

        doc.setDrawColor(226, 232, 240); // slate-200
        doc.line(margin, y + rowHeight, margin + contentWidth, y + rowHeight);

        let curX = margin;
        // SL #
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 116, 139);
        doc.text(String(idx + 1), curX + colWidths.sn / 2, y + 4.2, { align: 'center' });
        curX += colWidths.sn;

        // Category
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(51, 65, 85);
        const catStr = cleanPdfText(row.category);
        doc.text(catStr.length > 18 ? catStr.substring(0, 16) + '..' : catStr, curX + 2, y + 4.2);
        curX += colWidths.category;

        // Description lines
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(15, 23, 42);
        let lineY = y + 4.2;
        descLines.forEach((line: string) => {
          doc.text(line, curX + 2, lineY);
          lineY += 3.8;
        });
        curX += colWidths.desc;

        // Qty
        doc.setTextColor(71, 85, 105);
        doc.text(cleanPdfText(row.qty), curX + colWidths.qty / 2, y + 4.2, { align: 'center' });
        curX += colWidths.qty;

        // Rate
        doc.setTextColor(71, 85, 105);
        doc.text((row.rate || 0).toLocaleString(), curX + colWidths.rate - 2, y + 4.2, { align: 'right' });
        curX += colWidths.rate;

        // Total
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text((row.total || 0).toLocaleString(), curX + colWidths.total - 2, y + 4.2, { align: 'right' });

        y += rowHeight;
      });

      // Bottom Financial Audit & Settlement Totals
      if (y > pageHeight - 65) {
        doc.addPage();
        y = margin;
        drawQuotationHeader(false);
      }

      y += 4;

      // Summary Box (Notes on Left, Calculations on Right)
      const summaryBoxHeight = 44;
      const leftWidth = contentWidth * 0.54;
      const rightX = margin + leftWidth + 4;
      const rightWidth = contentWidth - leftWidth - 4;

      // Left Box: Notes & Terms
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(203, 213, 225);
      doc.roundedRect(margin, y, leftWidth, summaryBoxHeight, 1.5, 1.5, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(15, 23, 42);
      doc.text('TERMS & QUOTATION CONDITIONS', margin + 3, y + 5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.5);
      doc.setTextColor(71, 85, 105);

      const termsText = quotation.termsAndConditions ||
        '1. 30% advance booking deposit required to lock hall and room allocations.\n2. 50% payable 7 days prior to event date; remainder on event day.\n3. Outside catering or heavy AV requires prior management clearance.';
      const termsLines = doc.splitTextToSize(cleanPdfText(termsText), leftWidth - 6);
      doc.text(termsLines.slice(0, 7), margin + 3, y + 10);

      // Right Box: Financial Breakdown
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(rightX, y, rightWidth, summaryBoxHeight, 1.5, 1.5, 'FD');

      const financeRows: [string, string, boolean][] = [
        ['Subtotal Amount', `BDT ${(quotation.subtotal || 0).toLocaleString()}`, false],
        [
          quotation.discountAmount > 0 ? `Discount (${quotation.discountPercent}%)` : 'Discount',
          quotation.discountAmount > 0 ? `- BDT ${quotation.discountAmount.toLocaleString()}` : 'None',
          false
        ],
        [`Service Charge (${quotation.serviceChargePercent || 10}%)`, `+ BDT ${(quotation.serviceChargeAmount || 0).toLocaleString()}`, false],
        [`VAT / Tax (${quotation.taxPercent || 15}%)`, `+ BDT ${(quotation.taxAmount || 0).toLocaleString()}`, false],
        ['Estimated Grand Total', `BDT ${(quotation.grandTotal || 0).toLocaleString()}`, true],
        ['Required Advance Deposit (30%)', `BDT ${(quotation.depositRequired || 0).toLocaleString()}`, false]
      ];

      let finY = y + 5;
      financeRows.forEach(([lbl, val, isGrand]) => {
        if (isGrand) {
          doc.setFillColor(254, 243, 199); // amber-100
          doc.rect(rightX + 1, finY - 3.5, rightWidth - 2, 6, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(7.5);
          doc.setTextColor(180, 83, 9); // amber-700
        } else {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7);
          doc.setTextColor(71, 85, 105);
        }

        doc.text(cleanPdfText(lbl), rightX + 3, finY);
        doc.setFont('helvetica', 'bold');
        if (!isGrand) {
          doc.setTextColor(15, 23, 42);
        }
        doc.text(cleanPdfText(val), rightX + rightWidth - 3, finY, { align: 'right' });
        finY += 6.5;
      });

      y += summaryBoxHeight + 6;

      // Executive Authorization & Signatures
      if (y < pageHeight - 16) {
        y = Math.max(y, pageHeight - 20);
        doc.setDrawColor(203, 213, 225);
        doc.line(margin, y, margin + contentWidth, y);

        const sigW = contentWidth / 3;
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(71, 85, 105);

        doc.text('Prepared By: Banquet Sales Executive', margin + 2, y + 4.5);
        doc.text('Approved By: Convention & F&B Manager', margin + sigW + 2, y + 4.5);
        doc.text('Client Acceptance Signature', margin + sigW * 2 + 2, y + 4.5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6);
        doc.setTextColor(148, 163, 184);
        doc.text('Official Pro-Forma Event Proposal • Non-Binding Until Deposit Settlement', margin + 2, y + 8.5);
      }

      // Page numbering stamp pass
      const totalPages = doc.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(6.5);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${p} of ${totalPages}`, pageWidth - margin - 4, pageHeight - 5, { align: 'right' });
      }

      const cleanFilename = cleanPdfText(filename.toLowerCase().endsWith('.pdf') ? filename : `${filename}.pdf`).replace(/\s+/g, '_');
      return triggerPdfDownload(doc, cleanFilename, {
        title: `Banquet Quotation - ${serialNo}`,
        subject: `Event & Banquet Quotation for ${quotation.clientName || 'Valued Client'}`,
        author: resortName,
        creator: `${resortName} Sales & Events Management System`,
        keywords: `Quotation, Banquet, Convention, ${serialNo}, ${quotation.eventType || 'Event'}`
      });
    } catch (err) {
      console.error('Failed to export banquet quotation to PDF:', err);
      return false;
    }
  }
};
