import * as XLSX from 'xlsx';
import { ReportQueryResult } from './reportingService';

export interface CustomTableExportData {
  title: string;
  code?: string;
  category?: string;
  department?: string;
  dateRange?: string;
  columns: { key: string; header: string; align?: string; format?: string }[];
  rows: Record<string, any>[];
  summaryTotals?: Record<string, any>;
  metadata?: Record<string, any>;
}

/**
 * Enterprise Excel (.xlsx) and CSV (.csv) Export Engine
 * Generates styled, structured, non-blank spreadsheets with resort letterhead,
 * audit metadata, auto-sized columns, and summary totals.
 */
export const reportExportService = {
  /**
   * Export a standard ReportQueryResult to designed .xlsx spreadsheet
   */
  exportReportToExcel(result: ReportQueryResult, customFileName?: string): void {
    const fileName = customFileName || `CCULB_${result.definition.reportCode}_${new Date().toISOString().split('T')[0]}`;
    
    this.exportCustomTableToExcel({
      title: result.definition.reportName,
      code: result.definition.reportCode,
      category: result.definition.category,
      department: result.department || 'All Departments',
      dateRange: `Audited Period: ${new Date().toLocaleDateString('en-GB')}`,
      columns: result.columns,
      rows: result.rows,
      summaryTotals: result.summaryTotals,
      metadata: {
        'Generated By': result.generatedBy,
        'Generated At': result.generatedAt,
        'Data Source': result.definition.dataSource,
        'Scope': result.definition.defaultDataScope
      }
    }, fileName);
  },

  /**
   * Export a standard ReportQueryResult to clean, structured .csv file
   */
  exportReportToCSV(result: ReportQueryResult, customFileName?: string): void {
    const fileName = customFileName || `CCULB_${result.definition.reportCode}_${new Date().toISOString().split('T')[0]}`;

    this.exportCustomTableToCSV({
      title: result.definition.reportName,
      code: result.definition.reportCode,
      category: result.definition.category,
      department: result.department || 'All Departments',
      dateRange: `Audited Period: ${new Date().toLocaleDateString('en-GB')}`,
      columns: result.columns,
      rows: result.rows,
      summaryTotals: result.summaryTotals,
      metadata: {
        'Generated By': result.generatedBy,
        'Generated At': result.generatedAt,
        'Data Source': result.definition.dataSource
      }
    }, fileName);
  },

  /**
   * Export any tabular data to a designed multi-row Excel spreadsheet (.xlsx)
   */
  exportCustomTableToExcel(data: CustomTableExportData, fileName: string): void {
    const aoa: any[][] = [];

    // 1. Official Resort Letterhead
    aoa.push(['LESYNC RESORT & CONVENTION HALL - CCULB']);
    aoa.push(['Purbachal Link Road, Gazipur / Dhaka, Bangladesh | Tel: +880 1711-223344 | Email: accounts@lesyncresort.com']);
    aoa.push(['BIN / TIN: 002394819-0102 | Official Audited Management Information Report']);
    aoa.push([]); // blank line

    // 2. Report Details Header
    aoa.push(['REPORT TITLE:', data.title.toUpperCase()]);
    if (data.code) aoa.push(['REPORT CODE:', data.code, 'CATEGORY:', data.category || 'Management']);
    aoa.push([
      'BUSINESS DATE:', new Date().toLocaleDateString('en-GB'),
      'GENERATED:', new Date().toLocaleString(),
      'DEPARTMENT:', data.department || 'Resort Operations'
    ]);
    if (data.dateRange) aoa.push(['FILTER / PERIOD:', data.dateRange]);
    
    // 3. Summary / KPI Snapshot (if provided)
    aoa.push(['TOTAL RECORDS:', data.rows.length]);
    aoa.push([]); // blank line

    // 4. Column Header Row
    const headerRow = data.columns.map(c => c.header.toUpperCase());
    aoa.push(headerRow);

    // 5. Data Rows
    data.rows.forEach((row, idx) => {
      const rowValues = data.columns.map(col => {
        const val = row[col.key];
        if (val === undefined || val === null) return '—';
        if (typeof val === 'number') {
          return val;
        }
        return String(val);
      });
      aoa.push(rowValues);
    });

    // 6. Summary Totals Row (if exists)
    if (data.summaryTotals && Object.keys(data.summaryTotals).length > 0) {
      aoa.push([]); // spacing
      const totalRow = data.columns.map((col, idx) => {
        if (idx === 0) return data.summaryTotals![col.key] || 'TOTALS / AUDITED SUMMARY';
        const val = data.summaryTotals![col.key];
        if (val !== undefined && val !== null) return val;
        return '';
      });
      aoa.push(totalRow);
    }

    // 7. Audit & Verification Signatures
    aoa.push([]);
    aoa.push(['CONFIDENTIALITY NOTICE:', 'This document contains audited operational data from CCULB Resort PMS. Internal use only.']);
    aoa.push(['PREPARED BY: Duty Officer / System Operator', '', 'AUDITED BY: Internal Audit / Financial Controller', '', 'APPROVED BY: General Manager']);

    // Build worksheet from AOA
    const ws = XLSX.utils.aoa_to_sheet(aoa);

    // Auto-calculate column widths dynamically
    const colWidths = data.columns.map((col, colIdx) => {
      let maxLen = col.header.length;
      data.rows.forEach(r => {
        const val = r[col.key];
        if (val !== undefined && val !== null) {
          const str = typeof val === 'number' ? (val || 0).toLocaleString() : String(val);
          if (str.length > maxLen) maxLen = str.length;
        }
      });
      return { wch: Math.min(Math.max(maxLen + 4, 14), 45) };
    });
    ws['!cols'] = colWidths;

    // Create workbook and write file
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Audited Report');

    const cleanFileName = fileName.endsWith('.xlsx') ? fileName : `${fileName}.xlsx`;
    XLSX.writeFile(wb, cleanFileName);
  },

  /**
   * Export any tabular data to a well-formatted CSV with UTF-8 BOM
   */
  exportCustomTableToCSV(data: CustomTableExportData, fileName: string): void {
    let csv = '\uFEFF'; // UTF-8 Byte Order Mark for Excel compatibility

    // Header comment block
    csv += `# LESYNC RESORT & CONVENTION HALL - CCULB\n`;
    csv += `# Report: ${data.title} ${data.code ? `(${data.code})` : ''}\n`;
    csv += `# Category: ${data.category || 'General'} | Department: ${data.department || 'Operations'}\n`;
    csv += `# Generated: ${new Date().toLocaleString()} | Total Records: ${data.rows.length}\n`;
    if (data.dateRange) csv += `# Filter / Period: ${data.dateRange}\n`;
    csv += `# -------------------------------------------------------------------------\n`;

    // Column Headers
    const escapeCsv = (val: any): string => {
      if (val === undefined || val === null) return '""';
      const str = String(val);
      if (str.includes(',') || str.includes('"') || str.includes('\n')) {
        return `"${str.replace(/"/g, '""')}"`;
      }
      return str;
    };

    csv += data.columns.map(c => escapeCsv(c.header)).join(',') + '\n';

    // Rows
    data.rows.forEach(row => {
      const line = data.columns.map(col => {
        const val = row[col.key];
        return escapeCsv(val !== undefined && val !== null ? val : '—');
      }).join(',');
      csv += line + '\n';
    });

    // Summary Totals
    if (data.summaryTotals && Object.keys(data.summaryTotals).length > 0) {
      csv += `# -------------------------------------------------------------------------\n`;
      const totalsLine = data.columns.map((col, idx) => {
        const val = data.summaryTotals![col.key];
        if (idx === 0) return escapeCsv(val || 'TOTALS');
        return escapeCsv(val !== undefined ? val : '');
      }).join(',');
      csv += totalsLine + '\n';
    }

    // Trigger download
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', fileName.endsWith('.csv') ? fileName : `${fileName}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
};
